### ISSUE TITLE
R code 2.3 / 2.4 vary grid size

### ISSUE THREAD

**Issue by rlzijdeman** [rmcelreath/rethinking#103]
Hi, after code section 2.3 and 2.4 it is encouraged to change the grid size. However, this doesn't seem to work for me. In the code below I put the value of 'gridsize' in a variable to allow for easy replication / testing. For lower values, I get the following error when trying to plot the distribution (2.4):
``` 
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ 
```
Higher values don't provide an error, but a multi-model graph. I don't think I expected that either. Any comments / pointers are most welcome.

Best,

Richard

```
# section 2.3
## define grid
gridsize <- 10
p_grid <- seq( from = 0, to = 1, length.out = gridsize )

## define prior
prior <- rep( 1, gridsize )
# prior <- ifelse( p_grid < .5 , 0, 1)
# prior <- exp( -5 * abs( p_grid - .5 ))

## compute likelihood at each value in grid
likelihood <- dbinom( 6, size = 9 , prob = p_grid)

## compute product of likelihood and prior
unstd.posterior <- likelihod * prior

## standardize the posterior so it sums to 1
posterior <- unstd.posterior / sum(unstd.posterior)


# section 2.4
plot( p_grid, posterior, type = "b" ,
      xlab = "probability of water", ylab = "posterior probability" )
mtext ( paste(gridsize, "points" ))
```

**Comment by babeheim** [comment]
Hi Richard,
Check the spelling of `likelihod` vs `likelihood`.

**Comment by rlzijdeman** [comment]
omg... cheers ;)
