### ISSUE TITLE
Exercise 14E1 (page 439)

### ISSUE THREAD

**Issue by bjj103** [rmcelreath/rethinking#106]
Exercise 14E1 (on page 439) asks the student to model measurement error in the normally distributed independent variable, log_pop from the Oceanic tools data in chapter 10.  I tried extending this exercise to modeling error in the dependent variable **total_tools** instead, which is poisson.  But I get similar errors regardless of how I structure this in the below code.  Any suggestions?

I'd somewhat prefer to model the dependent variable, total_use, as having normally distributed error.  So, in the model below I replace the observed vector, total_tools, with a parameter vector, total_tools_est.  Total_tools_est takes total_tools as its mean and I assume a standard error of 2 (to keep things simple for now).   
```
m14.E1 <- map2stan(
  alist(
    total_tools_est ~ dpois(lambda),
    log(lambda) <- a + bp*log_pop + bc*contact_high + bpc*contact_high*log_pop,
    total_tools ~ dnorm(total_tools_est, 2),
    a ~ dnorm(0,100),
    c(bp,bc,bpc) ~ dnorm(0,1)
  ),
  data=d, start=list(total_tools_est=dlist$total_tools), WAIC=FALSE, chains=2 , cores=2 )
```
But map2stan doesn't like the above.  It throws an error, "no matches for: real ~ poisson(vector)." This makes sense to me because dnorm produces real numbers whereas dpois produces integers.  So, in response I thought that the following would serve as a correction.  Here I model total_tools as poisson (rather than normal) which should be more compatible and avoid the above error:
```
m14.E1 <- map2stan(
  alist(
    total_tools_est ~ dpois(lambda),
    log(lambda) <- a + bp*log_pop + bc*contact_high + bpc*contact_high*log_pop,
    total_tools ~ dpois(total_tools_est),
    a ~ dnorm(0,100),
    c(bp,bc,bpc) ~ dnorm(0,1)
  ),
  data=d, start=list(total_tools_est=dlist$total_tools), WAIC=FALSE, chains=2 , cores=2 )
```
But map2stan (or rstan) still doesn't like this and throws the same error "No matches for: real ~ poisson(vector)".  In other words, in the model above map2stan doesn't appear to pick up on the idea that total_tools is a poisson integer. 

Any suggestions for an error-in-variables model where the variables are poisson?

**Comment by rmcelreath** [comment]
Stan does not support discrete parameters. What you'd have to do is build a mixture model in Stan itself. There are some examples in the Stan manual. Details of code aside, I think what you have in mind is actually something like:
```
total_tools_obs ~ dbinom(total_tools_true,p)
total_tools_true ~ dpois(lambda)
```
where ``p`` is the probability of observing a tool, when it exists, and ``lambda`` is the true tool production rate. So this is like an "N-mixture" model used in ecology to monitor animal populations. To get the probability of total_tools_obs, we meed a mixture likelihood that averages over the unknown total_tools_true parameter.

Stan can do this. But map2stan definitely cannot. Yet. Sorry.

**Comment by bjj103** [comment]
Thanks Richard.  This is a great package (and book) that you've got here.
