### ISSUE TITLE
Crash when executing R code 13.22

### ISSUE THREAD

**Issue by pvdberg1** [rmcelreath/rethinking#108]
When running R code 13.22 from the book, I get the following error:

`Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection
Error in map2stan(alist(pulled_left ~ dbinom(1, p), logit(p) <- A + (BP +  : 
  Something went wrong in at least one chain. Debug your model while setting chains=1 and cores=1. Once the model is working with a single chain and core, try using multiple chains/cores again.
error writing to connection`

I tried running with chains=1, cores=1, but to no avail. R code 13.19 does run without problems.
I tried taking out one of the random factors (block) and only varying one of the slopes (only bp), so that I am back to a twodimensional multivariate Gaussian prior - same problem. I also tried the non-centered parameterization (R code 13.22), but this gives the same error.

I am running the latest version of R (3.4.1) and installed the latest versions of both Rstan and the rethinking package.

**Comment by rmcelreath** [comment]
To help, I would need the error message that you get when you run with a single chain.

**Comment by pvdberg1** [comment]
I actually get a windows popup when the crash happens (I get this popup 3 times if I run 3 cores/3 chains, and once if I run 1 core/1 chain):

![image](https://user-images.githubusercontent.com/30896737/30022068-f15c3d18-9169-11e7-88ed-32a4ce63a314.png

Next, the R session aborts if I ran a single chain - it doesn't abort if I ran 3 chains (it then gives the error message in my original post). 

Here is the '.txt' file referred to in the error message.

[WERE1F8.tmp.appcompat.txt](https://github.com/rmcelreath/rethinking/files/1274374/WERE1F8.tmp.appcompat.txt)

I cannot attach the 'dump' file here, but here's a screenshot from when I opened it - apparently the error is to do with reading/writing:

![image](https://user-images.githubusercontent.com/30896737/30022579-3432f972-916c-11e7-8236-f369dea137e7.png)

**Comment by rmcelreath** [comment]
This is pretty mysterious. But it is unlikely to have anything to do with my package, but rather is something about how rstan and Windows interact. This issue on the Stan forums looks like your issue:

http://discourse.mc-stan.org/t/rstan-crashes-after-first-iteration-on-one-of-two-windows-machines/736

It is marked "resolved", but I don't actually see a solution. Also look here:

http://discourse.mc-stan.org/t/rstan-sampling-r-session-aborted-error/1456

**Comment by pvdberg1** [comment]
Thanks - the second link actually helped me solve the problem. There the problem was that something was wrong with the 'Makevars' file that needs to be created when installing RStan. So I recreated this file, and now everything runs fine! Perhaps I didn't configure it properly when I re-installed R and RStan recently, in which case I apologize for wasting your time... Thanks for directing me to the right place, and -while I'm here- for writing the book; it really upgraded my statistics game on both a technical and a conceptual level.

**Comment by rmcelreath** [comment]
Awesome. This will be useful then the next time someone brings me that kind of error.

Will mark this closed.
