### ISSUE TITLE
sim and postcheck fail when using normal instead of dnorm

### ISSUE THREAD

**Issue by teodecarvalho** [rmcelreath/rethinking#117]
It looks like the functions sim and postcheck cannot handle models with distribution names from Stan (normal vs dnorm, cauchy vs dcaucy, ...).
Here is an reproducible example:
```{r}
library(rethinking)

x <- rnorm(10, 2, 5)
m1 <- map2stan(alist(
    mu ~ dnorm(0, 10),
    sigma ~ dcauchy(0, 5),
    x ~ dnorm(x_bar, sigma),
    x_bar <- mu
  ), data = list(x = x))

summary(m1)
sim(m1) # OK

m2 <- map2stan(alist(
  mu ~ normal(0, 10),
  sigma ~ normal(0, 5),
  x ~ cauchy(x_bar, sigma),
  x_bar <- mu
), data = list(x = x))

summary(m2)
sim(m2) # Fails with message: Error in rormal(10, 0, 10) : could not find function "rormal"
# The same happens with postcheck
```

First time reporting a bug, so let me know if further details should be given.

**Comment by rmcelreath** [comment]
Thanks for the report.

This is functionality I added already to the Experimental branch, I think. Relevant code:

https://github.com/rmcelreath/rethinking/blob/Experimental/R/sim.r#L196

Give it a try maybe and let me know if you encounter any other issues.
