### ISSUE TITLE
Tadpole example with rstanarm

### ISSUE THREAD

**Issue by marcomarconi** [rmcelreath/rethinking#122]
I was trying to replicate the tadpole example (m12.2) with rstanarm, in order to understand a little how multilevel models work, here is my code:

(I transformed tank to factor first!)
`fit<-stan_glmer(cbind(surv, density-surv)~(1|tank), data=d, family=binomial())`

however, estimates for intercept and sigma are different from those obtained with rethinking, what am I doing wrong?

thanks,

**Comment by rmcelreath** [comment]
I don't know which priors rstanarm is using, but it is not likely using exactly the same ones as the map2stan example code. So probably you are doing nothing wrong at all.
