### ISSUE TITLE
missing Poisson data - should "real CASES_merge[N]" be "int CASES_merge[N]"

### ISSUE THREAD

**Issue by olli0601** [rmcelreath/rethinking#127]
Hello Richard 

I am trying to handle missing Poisson data values with map2stan, but Rstan throws the error:

""
No matches for: 

  real[] ~ poisson(vector)
""

Looking at the stan code, should "real CASES_merge[N]" be "int CASES_merge[N]" in the following:

data{
    int<lower=1> N;
    int<lower=1> N_missing;
    int CASES_PER_MONTH[N];
    int CASES_PER_MONTH_missingness[N_missing];
}
transformed parameters{
    real CASES_PER_MONTH_merge[N];
    CASES_PER_MONTH_merge = CASES_PER_MONTH;
    for ( u in 1:N_missing ) CASES_PER_MONTH_merge[CASES_PER_MONTH_missingness[u]] = CASES_PER_MONTH_impute[u];
}

Thanks!

Oliver

**Comment by rmcelreath** [comment]
Imputing Poisson variables is not supported directly. Stan does not sample discrete variables. So you'd need to code it up as a marginalization.

In the Experimental branch, map2stan will construct the marginalization for binary variables. But nothing yet for Poisson variables. In principle, it is the same of course. But lots more terms!

Anyway, sorry that I just don't know when I'll get a chance to work on this.

If the variable is just a predictor, then probably no harm in just treating it as a truncated normal and doing the imputation on that basis.

**Comment by olli0601** [comment]
Thank you for the fast response. This is much clearer now. 

It s not a high priority for me, no need to work on this, and I will try and find a workaround.

Best, Oliver
