### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ColleenRossier** [rmcelreath/rethinking#13]
Dear Richard and others,

I have installed rstan, but when I try to install rethinking, I get the following error:

ERROR: dependency 'loo' is not available for package 'rethinking'
removing 'C:/Users/drlabuser/Documents/R/win-library/3.1/rethinking'
Error: Command failed (1)

Any suggestions welcome!

Thank you,
Colleen

**Comment by bbolker** [comment]
try `install.packages("loo")` and then try installing `rethinking` again ... ?

**Comment by jgabry** [comment]
Did that end up solving the problem? If not, I guess it's possible that
your CRAN mirror hasn't updated, as I just added an update to loo on CRAN a
few days ago. But I think both source and binary are already up. And if
you're using the RStudio mirror then I definitely don't think that's the
issue.

If you want you can install loo from GitHub using

devtools::install_github("jgabry/loo")

Hope that helps.

**Comment by ColleenRossier** [comment]
Thank you all for your quick responses! My issue was that my R was not up to date, and loo requires 3.2.2.
