### ISSUE TITLE
Mistake in "Overthinking: How strong is a prior?"

### ISSUE THREAD

**Issue by mmclaren42** [rmcelreath/rethinking#133]
On p. 89, the discussion of how much data you would need to observe makes no mention of the standard deviation of the data you are observing. The box reaches the conclusion you would need to observe 100 heights with mean 178 to have a posterior with a standard deviation of 0.1, but this is only true if the heights you observed also had the rather narrow standard deviation of 1.

**Comment by rmcelreath** [comment]
It says exactly that in the box.
