### ISSUE TITLE
Parsing bug in map2stan for m14.1

### ISSUE THREAD

**Issue by pboesu** [rmcelreath/rethinking#137]
I was just rerunning example model m14.1 from the book (as part of troubleshooting a different measurement error model I am developing in stan directly), and came across an unexpected bug in `map2stan`. Unexpected, because I specifically remember running this example successfully about 18 months ago when I first started working with measurement error models.

It also took me a couple of runs to figure out that there was a bug in the first place, since `map2stan` creates syntactically valid stan code (but for an incorrect model) .

In essence, `map2stan` doesn't propagate variable dimensions for the latent state `div_est` across model hierarchies, but makes it a scalar instead.

The bug occurs for me in both the release and experimental branch, example R and stan code and sessionInfo() output below.

```
library(rethinking)
#observation error models (chapter 14)
data(WaffleDivorce)
d3 <- WaffleDivorce

dlist <- list(
  div_obs = d3$Divorce,
  div_sd = d3$Divorce.SE,
  R = d3$Marriage,
  A = d3$MedianAgeMarriage
)

m14.1 <- map2stan(
  alist(
    div_est ~ dnorm(mu, sigma),
    mu <- a + bA*A + bR*R,
    div_obs ~ dnorm(div_est, div_sd),
    a ~ dnorm(0,10),
    bA ~ dnorm(0,10),
    bR ~ dnorm(0, 10),
    sigma ~ dcauchy(0,2.5)
  ),
  data = dlist,
  sample = FALSE,
  iter = 2000
)

stancode(m14.1)
```

Gives me the following stan code (comment added in parameters block), where `div_est` is declared as a real scalar, rather than a real array of length N.

```
//2018-05-18 15:02:44
data{
    int<lower=1> N;
    real div_obs[N];
    real R[N];
    real A[N];
    real div_sd[N];
}
parameters{
    real div_est; // <-- this should really be a one dimensional array of length N
    real a;
    real bA;
    real bR;
    real<lower=0> sigma;
}
model{
    vector[N] mu;
    sigma ~ cauchy( 0 , 2.5 );
    bR ~ normal( 0 , 10 );
    bA ~ normal( 0 , 10 );
    a ~ normal( 0 , 10 );
    div_obs ~ normal( div_est , div_sd );
    for ( i in 1:N ) {
        mu[i] = a + bA * A[i] + bR * R[i];
    }
    div_est ~ normal( mu , sigma );
}
generated quantities{
    vector[N] mu;
    for ( i in 1:N ) {
        mu[i] = a + bA * A[i] + bR * R[i];
    }
}
```

<details>
<summary>sessionInfo()</summary>

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rethinking_1.72    rstan_2.17.3       StanHeaders_2.17.2 ggplot2_2.2.1     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16       matrixStats_0.53.1 mvtnorm_1.0-7      lattice_0.20-35    MASS_7.3-49       
 [6] grid_3.5.0         plyr_1.8.4         gtable_0.2.0       stats4_3.5.0       coda_0.19-1       
[11] scales_0.5.0       pillar_1.2.2       rlang_0.2.0        lazyeval_0.2.1     tools_3.5.0       
[16] loo_2.0.0          munsell_0.4.3      compiler_3.5.0     inline_0.3.14      colorspace_1.3-2  
[21] gridExtra_2.3      tibble_1.4.2     
```
</details>

**Comment by pboesu** [comment]
I see, thank you!

Is there a a general rule when a size declaration in this manner is necessary for map2stan?

**Comment by rmcelreath** [comment]
map2stan gets the dimension of a parameter either from an index variable like [dept] or from explicit size in a start list. Some distributions enforce certain dimensions, like multi_normal enforcing the right size for correlation matrix.

I have in mind adding some optional syntax to make explicit typing and sizing possible. Something like:

```
div_est[div_obs] ~ dnorm( mu , sigma )
```
And that would mean "one div_est for each div_obs".
