### ISSUE TITLE
Convert to coda?

### ISSUE THREAD

**Issue by puterleat** [rmcelreath/rethinking#14]
Is it possible to convert map2stan model fit objects to coda objects, as it is for standard stan objects (e.g. http://jeromyanglim.tumblr.com/post/91434443911/how-to-convert-a-stan-fit-object-to-work-with-coda)

**Comment by puterleat** [comment]
Apologies, I've just answered my own question with some basic digging... For ref, the stanfit object is available as an attribute on the map2stan instance:

    attr(model, "stanfit")

**Comment by rmcelreath** [comment]
Right. I should add a method perhaps to extract the stanfit object, so people don't have to hunt it down in the internal structure. Perhaps extract_stanfit or such.

**Comment by puterleat** [comment]
That would be good... perhaps I'm biased by having just wanted to do it, but a "to_coda" method would also be helpful.
