### ISSUE TITLE
Link function output very different from textbook

### ISSUE THREAD

**Issue by xue-jun** [rmcelreath/rethinking#144]
I was trying to replicate R code 4.53 in page 104, Statistical Rethinking. I used the below code:

`library('rethinking')
library(repr)
data(Howell1)
d <- Howell1
d2 <- d[d$age >= 18, ]

m4.3 <- map(
alist(
height ~ dnorm( a + b*weight, sigma),
a ~ dnorm(178, 100),
b ~ dnorm(0, 10),
sigma ~ dunif(0, 50)
),
data=d2)
precis(m4.3)

mu <- link(m4.3)
str(mu)`

The precis function matches the book, but for the link function, the resulting values are between 20 and 70, much lower than the values in the book. The discrepancy seems to be the same magnitude as the intercept.

**Comment by rmcelreath** [comment]
If you want to use link, you should use a linear model. This means here defining mu <- a + b*weight.

**Comment by xue-jun** [comment]
Got it. I added mu <- a + b*weight in the alist, and replaced a+b*weight in the dnorm function with mu, now it matches the book. Thanks.
