### ISSUE TITLE
WAIC error

### ISSUE THREAD

**Issue by mfries1963** [rmcelreath/rethinking#146]
standardize <- function(x){
  (x - mean(x))/sd(x)
}
data("Howell1")
d <- Howell1
# standerdizing the age
d$age <- standardize(d$age)
# sets random seed
set.seed(1000)

m6e1 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b_1 * age,
    a ~ dnorm(138, 3*27),
    b_1 ~ dnorm(0,5)
  ),
  data = d1
)
DIC(m6e_1)
WAIC(m6e_1)

This code returns:

> DIC(m6e_1)
[1] 62591.38
attr(,"pD")
[1] 1.953919
> WAIC(m6e_1)
Constructing posterior predictions
[ 1000 / 1000 ]
Error in sim_out[s, ] <- eval(parse(text = xeval), envir = e) : 
  number of items to replace is not a multiple of replacement length

**Comment by rmcelreath** [comment]
Put a reasonable prior on sigma maybe.
