### ISSUE TITLE
Return named list from WAIC

### ISSUE THREAD

**Issue by lstmemery** [rmcelreath/rethinking#149]
Right now, If I want to access the `lppd` of WAIC I have to do this:

```r
attributes(waic)$lppd
# OR
attr(waic, "lppd")
```

Instead, I propose that a named list should be returned.

```r
waic[["lppd"]]
```

Justification is here: https://stackoverflow.com/a/6457376

Since this is a design change that would break the previous code, I'm submitting this as an issue but I'd be willing to write the PR myself.

**Comment by lstmemery** [comment]
Side note: @rmcelreath your book is fantastic. I saw that you are writing the 2nd edition. If you would like help with the Python translation, I'd love to be of service.

**Comment by rmcelreath** [comment]
I agree. I plan to rewrite the methods so they return custom objects that descend from list. This will help with display (show) as well.
