### ISSUE TITLE
getting scale right

### ISSUE THREAD

**Issue by jojensen890** [rmcelreath/rethinking#158]
Hi there,
I am creating a model to predict the age of trees from their height. However, in my data set, age is gamma distributed. To accommodate the gamma likelihood, I made this model: 

`fit2<- map(
  alist(
    age ~ dgamma2(mu, scale),
    log(mu) <- b + m*height,
    b ~ dnorm(16.3759, 10),
    m ~ dnorm(10.9808, 10),
    scale ~ dexp(2)
  ),
  data = d
)`

However, I am concerned that "scale" isn't normally distributed and thus I can't use extract.samples() to samples the multi-dimensional posterior. I believe if I log the scale parameter, it becomes normal and thus using extract.samples() will work. 

How do I modify the code above to do this? I've seen this done in other examples with dbetabinom() but never with dgamma2(). 

Thanks for any and all help!!

Edit: Note: So sorry, I'm new to GitHub and now I'm realizing this isn't an "Issue" it's just a question. I can post this on stack exchange! Sorry! But if you want to help, I'd appreciate it as I pour over your book for clues!

**Comment by rmcelreath** [comment]
I think you can just use `dgamma2(mu, exp(log_scale))` and then give `log_scale` a normal prior? Or you could use map2stan instead, where the non-normality isn't a problem.
