### ISSUE TITLE
re-using compiled model

### ISSUE THREAD

**Issue by puterleat** [rmcelreath/rethinking#16]
Is there a way to make map2stan re-use a compiled model with new data? 

I know it's possible to extract the stanfit object and use that, but I'm running a simulation study and would like to be able to re-use the map2stan object to fit new data and then use post() simulate data from these fitted values.

**Comment by rmcelreath** [comment]
Yes, it is still undocumented, because I haven't written tests for it. But you can pass a previous map2stan object to map2stan() and it will reuse the compiled model inside the stanfit slot. For example:
```
library(rethinking)
data(chimpanzees)

# don't want any variables with NAs
d <- list( 
    pulled_left = chimpanzees$pulled_left ,
    prosoc_left = chimpanzees$prosoc_left ,
    condition = chimpanzees$condition ,
    actor = as.integer( chimpanzees$actor ) ,
    blockid = as.integer( chimpanzees$block )
)

m2 <- map2stan(
    alist(
        pulled_left ~ dbinom(1,theta),
        logit(theta) <- a + bp*prosoc_left + bpc*condition*prosoc_left ,
        a ~ dnorm(0,10),
        bp ~ dnorm(0,10),
        bpc ~ dnorm(0,10)
    ) ,
    data=d, chains=1, cores=1 )

m2again <- map2stan( m2 , chains=4 , cores=4 )
```
There is also a deprecated older function, resample(), that has similar functionality.

**Comment by rmcelreath** [comment]
P.S.: It can take a new data list. That wasn't obvious from my example.
