### ISSUE TITLE
issues with link()

### ISSUE THREAD

**Issue by Rdk0** [rmcelreath/rethinking#160]
I have had a problem with reproducing the results from the book, both codes are using rethinking::link().

## R code 4.53
mu <- link( m4.3 )  
[ 1000 / 1000 ]
 num [1:1000, 1:352] 47.8 45.4 42 43 41.9 ... 

## R code 4.54
mu <- link( m4.3 , data=data.frame(weight=weight.seq) )

[ 1000 / 1000 ]
 num [1:1000, 1:46] 22.4 21.4 22.8 21.2 24 ...

I have ended up adopting 4.58 code to replace of rethinking::link()

**Comment by Riadsala** [comment]
Some of the students in my class are having exactly the same problem. 

Is there a simple fix for this?

**Comment by rmcelreath** [comment]
I suspect that your students are using m4.3 from ## R code 4.39 instead of ## R code 4.38. The map model needs an explicit linear model in it, the mu symbol, for link to work as expected.
