### ISSUE TITLE
Trying to estimate the parameters of a normal distribution with map2stan gives a strange error message

### ISSUE THREAD

**Issue by lbagua** [rmcelreath/rethinking#164]
I tried a very simple example using map2stan and I got a strange error.
This was the example:
-----------------------
y <- rnorm(100,0,2)
dn <- list(y=y)
-----------------------
If I use "map" there is no problem:
-----------------------
m1 <- map( alist(
  y ~ dnorm( mu , sigma ) ,
  mu ~ dnorm(0,5),
  sigma ~ dunif( 0 , 50 )), data=dn)
precis(m1)
-----------------------

However, when I used map2stan:
-----------------------
ms1 <- map2stan( alist(
  y ~ dnorm( mu , sigma ),
  mu <- dnorm(0,5),
  sigma ~ dunif( 0 , 50 )), data=dn,
  warmup=2000 , iter=5000 , chains=2 
)
-----------------------
I got the following error message:
-----------------------
Computing WAIC
Constructing posterior predictions
Error in .local(fit, data, n, ...) : 
  There appear to be no linear models here
In addition: Warning messages:
1: There were 1 divergent transitions after warmup. Increasing adapt_delta above 0.8 may help. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup 
2: Examine the pairs() plot to diagnose sampling problems
-----------------------
This is the code in Stan:
-----------------------
> stancode(ms1)
data{
    int<lower=1> N;
    real y[N];
}
parameters{
    real mu;
    real<lower=0,upper=50> sigma;
}
model{
    // sigma ~ uniform( 0 , 50 );
    mu ~ normal( 0 , 5 );
    y ~ normal( mu , sigma );
}
generated quantities{
    real dev;
    dev = 0;
    dev = dev + (-2)*normal_lpdf( y | mu , sigma );
}
-----------------------
(why is sigma commented out?)
However, if I use the above code directly with stan, it ran:
-----------------------

dn <- list(N=length(y),y=y)
mss1 <- '
data{
    int<lower=1> N;
    real y[N];
}
parameters{
    real mu;
    real<lower=0,upper=50> sigma;
}
model{
    // sigma ~ uniform( 0 , 50 );
    mu ~ normal( 0 , 5 );
    y ~ normal( mu , sigma );
}
generated quantities{
    real dev;
    dev = 0;
    dev = dev + (-2)*normal_lpdf( y | mu , sigma );
}
'
res.mss1 <- stan(model_code = mss1, data = dn, warmup =2000, iter = 5000, chains = 2)
-----------------------
I can avoid the problem with a small trick:
-----------------------
ms1 <- map2stan( alist(
  y ~ dnorm( mu , sigma ),
  mu <- a,
  a ~ dnorm(0,5),
  sigma ~ dunif( 0 , 50 )), data=dn,
  warmup=2000 , iter=5000 , chains=2 
) 
-----------------------
But it is not clear to me what is going on. Does this mean map2stan always requires a "regression" structure? In fact the error message says "There appear to be no linear models here"
Any help is most welcome.

**Comment by rmcelreath** [comment]
It is the WAIC calculation that throws the error. You can set WAIC=FALSE.
