### ISSUE TITLE
On install ver. 1.88: lppd, cvquap, dagitty::paths, graphLayout links missing

### ISSUE THREAD

**Issue by jedijd** [rmcelreath/rethinking#167]
I tried multiple times to install > install_github("rmcelreath/rethinking",ref="Experimental", force = TRUE)
Downloading GitHub repo rmcelreath/rethinking@Experimental
√  checking for file 'C:\Users\kurts\AppData\Local\Temp\RtmpS8Zohw\remotes2cc0740d59b4\rmcelreath-rethinking-2ce24c8/DESCRIPTION' ... 
-  preparing 'rethinking':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'rethinking_1.88.tar.gz'
   
* installing *source* package 'rethinking' ...
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'rethinking'
    finding HTML links ... done
    AMTL                                    html  
    Achehunting                             html  
    Crofoot                                 html  
    Dinosaurs                               html  
    Dissertations                           html  
    Fish                                    html  
    HPDI                                    html  
    finding level-2 HTML links ... done

    Hoogland                                html  
    Hurricanes                              html  
    Kline                                   html  
    KosterLeckie                            html  
    Primates301                             html  
    PrussianHorses                          html  
    Rinder                                  html  
    Trolley                                 html  
    UFClefties                              html  
    WAIC                                    html  
    WaffleDivorce                           html  
    Wines2012                               html  
    bangladesh                              html  
    chainmode                               html  
    cherry_blossoms                         html  
    chimpanzees                             html  
    coeftab                                 html  
    coeftab.plot                            html  
    coerce_index                            html  
    col.alpha                               html  
    compare                                 html  
    contour.xyz                             html  
    dbetabinom                              html  
    dens                                    html  
    dgampois                                html  
    dlkjcorr                                html  
    dmvnorm2                                html  
    dordlogit                               html  
    drawdag                                 html  
Rd warning: C:/Users/kurts/AppData/Local/Temp/Rtmpm8fDyW/R.INSTALL43c028d6589/rethinking/man/drawdag.Rd:35: missing link 'graphLayout'
Rd warning: C:/Users/kurts/AppData/Local/Temp/Rtmpm8fDyW/R.INSTALL43c028d6589/rethinking/man/drawdag.Rd:37: missing link 'dagitty::paths'
    dzagamma2                               html  
    dzibinom                                html  
    dzipois                                 html  
    ensemble                                html  
    extract.samples                         html  
    foxes                                   html  
    glimmer                                 html  
    image.xyz                               html  
    link                                    html  
    log_sum_exp                             html  
    map2stan-class                          html  
    map2stan                                html  
    mcreplicate                             html  
    milk                                    html  
    pairs.map2stan                          html  
    plot.map2stan                           html  
    postcheck                               html  
    precis                                  html  
    progbar                                 html  
    quap                                    html  
    resample                                html  
    rethinking-internal                     html  
    rethinking                              html  
    sample.naive.posterior                  html  
    shade                                   html  
    sim                                     html  
    sim.train.test                          html  
Rd warning: C:/Users/kurts/AppData/Local/Temp/Rtmpm8fDyW/R.INSTALL43c028d6589/rethinking/man/sim.train.test.Rd:40: missing link 'lppd'
Rd warning: C:/Users/kurts/AppData/Local/Temp/Rtmpm8fDyW/R.INSTALL43c028d6589/rethinking/man/sim.train.test.Rd:40: missing link 'cv_quap'
    simplehist                              html  
    ulam                                    html  
** building package indices
** testing if installed package can be loaded
* DONE (rethinking)
Making 'packages.html' ... done
In R CMD INSTALL

**Comment by rmcelreath** [comment]
There doesn't appear to be any issue here.

**Comment by jedijd** [comment]
Remarkably fast response! Thanks. I assumed that the missing links would lead to trouble down the road. But I've never built an R package and it's your package so I'll take your word for it that these warnings don't present any issue.
