### ISSUE TITLE
unexpected behavior in rlkjcorr

### ISSUE THREAD

**Issue by davharris** [rmcelreath/rethinking#17]
Hi Richard, hope you're having a great time in Germany.

My understanding of the LKJ correlation matrix was that the shape parameter should have a consistent interpretation (e.g. eta==1 implies uniform) regardless of the number of dimensions.  In version 1.58 of the rethinking package, I'm not finding that to be the case.

If I run the example with K==2 and eta==1, I get a uniform distribution, as expected.  But if I change K to 20, I get a bell-shaped curve with SD≈0.2.

```
library(rethinking)
R <- rlkjcorr(1e4,K=20,eta=1)
dens( R[,1,2] )
```

**Comment by rmcelreath** [comment]
I think this is the expected behavior. eta=1 is uniform over matrices, not correlations. So even with K=3, you'll see concentration of mass around rho=0, just because it's not possible to build valid matrices with independent correlations.
```
library(rethinking)
R <- rlkjcorr(1e4,K=3,eta=1)
plot( R[,1,2] , R[,1,3] , col=col.alpha("black",0.2) , pch=16 )
```
The Stan functions behave the same way:
```
mc <- "
parameters{
    corr_matrix[3] Rho;
}
model{
    Rho ~ lkj_corr(1);
}"
m <- stan(model_code=mc,chains=1,warmup=100,iter=1e4)
R <- extract.samples(m)$Rho
plot( R[,1,2] , R[,1,3] , col=col.alpha("black",0.2) , pch=16 )
```

**Comment by jgabry** [comment]
Indeed, even in 3 dimensions the space of possible correlation
matrices looks like a stuffed Dorito rather than a full cube.

**Comment by davharris** [comment]
Ah, you're right.  I mis-remembered or misunderstood the Stan documentation.  Sorry for the false alarm.

Hope you're enjoying Germany!
