### ISSUE TITLE
documentation for reedfrogs data set?

### ISSUE THREAD

**Issue by bbolker** [rmcelreath/rethinking#170]
As far as I can tell the `reedfrogs` data set is undocumented **in the package** (what's in the book is fine ...)
![reedfrog_rethink](https://user-images.githubusercontent.com/78918/57251705-7c648800-7018-11e9-9c3e-41b28065fb6d.png)

Would it be possible to add documentation (e.g. copy whatever you like from [here](https://github.com/bbolker/emdbook/blob/master/man/Reedfrog.Rd) ?) That way when the data get used in examples (like [this one](https://blogs.rstudio.com/tensorflow/posts/2019-05-06-tadpoles-on-tensorflow/)) that don't come directly from the book, readers will be able to know who collected the original data (James Vonesh, not me!) and trace the data back to their original source ... (see this [very nice blog post](https://blogs.rstudio.com/tensorflow/posts/2019-05-06-tadpoles-on-tensorflow/) about data provenance - I think this has also been discussed elsewhere ...)

If you prefer I could get around to submitting a PR sometime soon ...

PS I was a bit surprised that it seems to be possible to provide data *without* documenting them at all ? i.e. `library(rethinking); data(reedfrogs); head(reedfrogs)` works fine (of course), but `?reedfrogs` returns "No documentation for ‘reedfrogs’ in specified packages and libraries"

**Comment by rmcelreath** [comment]
Thanks, Ben. Definitely an oversight. I'll roll this into the next push.

**Comment by rmcelreath** [comment]
Just pushed this. https://github.com/rmcelreath/rethinking/commit/ed379d713633a32a9c2cdc33c667db3ca71ec86c
