### ISSUE TITLE
Cannot install the rethinking package: 

### ISSUE THREAD

**Issue by windtotem** [rmcelreath/rethinking#174]
Hello, I tried to install the rethinking packet after successfully installed the rstan package on R 3.6.0 on Windows 10. The console reports:

> checking for file 'C:\Users\xyx\AppData\Local\Temp\RtmpSoBOTU\remotes198c790d4259\rmcelreath-rethinking-1def057/DESCRIPTION' ...
√  checking for file 'C:\Users\xyx\AppData\Local\Temp\RtmpSoBOTU\remotes198c790d4259\rmcelreath-rethinking-1def057/DESCRIPTION'
-  preparing 'rethinking':
   checking DESCRIPTION meta-information ...
   checking DESCRIPTION meta-information ... 
√  checking DESCRIPTION meta-information
Warning in .write_description(db, ldpath) :
   Warning in .write_description(db, ldpath) :
     Unknown encoding with non-ASCII data: converting to ASCII
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added 
-  building 'rethinking_1.59.tar.gz'
Installing package into ‘C:/Users/xyx/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'rethinking' ...
** using staged installation
Error in file(file, if (append) "a" else "w") : 
  (converted from warning) cannot open file 'C:/Users/xyx/Documents/R/win-library/3.6/00LOCK-rethinking/00new/rethinking/DESCRIPTION': No such file or directory
ERROR: installing package DESCRIPTION failed for package 'rethinking'
* removing 'C:/Users/xyx/Documents/R/win-library/3.6/rethinking'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/xyx/AppData/Local/Temp/RtmpSoBOTU/file198c20ad391a/rethinking_1.59.tar.gz’ had non-zero exit status

I tried to manually add the mentioned directory and copy the DESCRIPTION from github to the directory and the error information became:

> ERROR: failed to lock directory 'C:/Users/xyx/Documents/R/win-library/3.6' for modifying
Try removing 'C:/Users/xyx/Documents/R/win-library/3.6/00LOCK-rethinking'

How can I fix this problem?

**Comment by dr-jojo** [comment]
I have also had problems with the rethinking package. But my seems to work fine now. There are a couple of ways to install it, and I pasted the one that seems to work most consistently for me. Hope it works. 

install.packages(c("mvtnorm","loo","coda"), repos="https://cloud.r-project.org/",dependencies=TRUE)
options(repos=c(getOption('repos'), rethinking='http://xcelab.net/R'))
install.packages('rethinking',type='source')

**Comment by cbrown5** [comment]
Hi there, I tried to install via devtools and it failed also, but for a different reason (a version conflict, I'm using R 3.6.0, but rethinking was developed for an older version). Anyway, trying @dr-jojo solution above worked perfectly. Thank you!

**Comment by dr-jojo** [comment]
Glad to hear that worked for others. I have been trying to install the experimental version (code below) but have failed every single time. I wonder if it is an issue with getting it from github  or devtools. If anybody has gotten the experimental version to work with different code that would be great if you could post it here.



install.packages(c("devtools","mvtnorm","loo","coda"),dependencies=TRUE)
library(devtools)
install_github("rmcelreath/rethinking",ref="Experimental")

**Comment by rmcelreath** [comment]
If you can copy the error message, we might be able to help.

**Comment by dr-jojo** [comment]
I have gotten a couple of different errors. Here is the most recent one, where it seems to get hung up on mvtnorm.

 library(devtools)
> install_github("rmcelreath/rethinking",ref="Experimental")
Downloading GitHub repo rmcelreath/rethinking@Experimental
These packages have more recent versions available.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: pkgbuild (1.0.3 -> 1.0.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
mvtnorm  (NA    -> 1.0-11) [CRAN]
pkgbuild (1.0.3 -> 1.0.4 ) [CRAN]
Installing 2 packages: mvtnorm, pkgbuild
Installing packages into ‘C:/Users/JoJo/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/mvtnorm_1.0-11.zip'
Content type 'application/zip' length 271076 bytes (264 KB)
downloaded 264 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/pkgbuild_1.0.4.zip'
Content type 'application/zip' length 134513 bytes (131 KB)
downloaded 131 KB

package ‘mvtnorm’ successfully unpacked and MD5 sums checked
Error: Failed to install 'rethinking' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘mvtnorm’

**Comment by rmcelreath** [comment]
First thing I'd try is installing mvtnorm by itself. That looks like the problem. install.packages('mvtnorm')

Second thing I'd try is to completely clean out your R installation and start over. Seems like your library is corrupt. It's not a problem with my package, in any event.

**Comment by dr-jojo** [comment]
It think you might have been right. I uninstalled everything twice and on the second time it worked. Thank you so much, loving the package!

**Comment by leomarameo7** [comment]
Please, I have a conflict with installing rethinking.  I tried to initiate "packrat", with my existing project, but here's the error: 
> packrat::init()
Initializing packrat project in directory:
- "~/Desktop/functional_response_herbivore_fish"
Error: Unable to retrieve package records for the following packages:
- 'rethinking'
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  Package 'rethinking' not available in repository or locally
2: In FUN(X[[i]], ...) :
  Failed to infer source for package 'bdsmatrix'; using latest available version on CRAN instead

### So I follow https://github.com/rstudio/packrat/issues/553#issuecomment-486552518 , but it did not solve the problem. 

### Line command###
> options(repos=c(getOption('repos'), rethinking='http://xcelab.net/R'))
> install.packages('rethinking',type='source')
Installing package into ‘/Users/leonardocapitani/Library/R/3.6/library’
(as ‘lib’ is unspecified)
trying URL 'http://xcelab.net/R/src/contrib/rethinking_2.00.tar.gz'
Content type 'application/x-tar' length 2241087 bytes (2.1 MB)
==================================================
downloaded 2.1 MB
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'packrat/init.R': No such file or directory
Execution halted
Warning in install.packages : installation of package ‘rethinking’ had non-zero exit status
The downloaded source packages are in
‘/private/var/folders/p4/f6_qlcws5bn0t43ytfhf18x00000gn/T/RtmpXDBdZO/downloaded_packages’

####My hardware: 
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

**Comment by jsgutierrezd** [comment]
Hi everybody. 

Can you help me with this issue, please?

I´m trying to install rethinking package and I´m getting this error:

"Error: Failed to install 'rethinking' from GitHub:
  (converted from warning) installation of package ‘C:/Users/sebas/AppData/Local/Temp/Rtmp06ZhQN/file129474cf2acb/rethinking_2.01.tar.gz’ had non-zero exit status"

How can I fix this problem?

Thanks!!!!

**Comment by bosafoagyare** [comment]
@jsgutierrezd I had similar issue and this resolved it for me:

`install.packages(c("coda","mvtnorm","devtools"))
library(devtools)
devtools::install_github("rmcelreath/rethinking")`

These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                              
 2: CRAN packages only               
 3: None                             
 4: isoband   (0.2.0 -> 0.2.1) [CRAN]
 5: rlang     (0.4.5 -> 0.4.6) [CRAN]
 6: scales    (1.1.0 -> 1.1.1) [CRAN]
 7: tibble    (3.0.0 -> 3.0.1) [CRAN]
 8: withr     (2.1.2 -> 2.2.0) [CRAN]
 9: ellipsis  (0.3.0 -> 0.3.1) [CRAN]
10: pillar    (1.4.3 -> 1.4.4) [CRAN]
11: vctrs     (0.2.4 -> 0.3.0) [CRAN]
12: pkgbuild  (1.0.6 -> 1.0.8) [CRAN]
13: backports (1.1.6 -> 1.1.7) [CRAN]
14: ps        (1.3.2 -> 1.3.3) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
**3**
I chose option **3**. Hope this helps

**Comment by chaz23** [comment]
I'm having some trouble as well installing the rethinking package. These are the error message I'm getting, any help would be appreciated.

`> devtools::install_github("rmcelreath/rethinking")
Error: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Connection timed out after 10010 milliseconds`

Then I tried:

`library(httr)
with_config(use_proxy("...", "..."), install_github("rmcelreath/rethinking"))`

And I got:

`Downloading GitHub repo rmcelreath/rethinking@HEAD
/3.5/bin/tar: Child returned status 127
/3.5/bin/tar: Error is not recoverable: exiting now
External tar failed with `--force-local`, trying without
/3.5/bin/tar: Child returned status 127
/3.5/bin/tar: Error is not recoverable: exiting now
External tar failed with `--force-local`, trying without
Error: Failed to install 'rethinking' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)`

Unfortunately I can't try `options(repos=c(getOption('repos'), rethinking='http://xcelab.net/R'))` as it is blocked by my company's firewall.

Any advice on how to fix this issue? :)

**Comment by rmcelreath** [comment]
Maybe some network issue? Can you just download the release and install from local? https://github.com/rmcelreath/rethinking/releases/tag/2.13

Anyway, it seems to be something about your network and not my package, so I can't provide any detailed help I'm afraid.

**Comment by znaroor** [comment]
I'm having issues loading Rethink, This is error I keep getting: 

> library(devtools)
> install_github("rmcelreath/rethinking",ref="Experimental")
Downloading GitHub repo rmcelreath/rethinking@Experimental
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: digest (0.6.26 -> 0.6.27) [CRAN]
5: V8     (3.2.0  -> 3.3.1 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:2
digest (0.6.26 -> 0.6.27) [CRAN]
V8     (3.2.0  -> 3.3.1 ) [CRAN]
shape  (NA     -> 1.4.5 ) [CRAN]
Installing 3 packages: digest, V8, shape
Error: Failed to install 'rethinking' from GitHub:
  (converted from warning) unable to access index for repository http://xcelab.net/R/bin/macosx/contrib/4.0:
  cannot open URL 'http://xcelab.net/R/bin/macosx/contrib/4.0/PACKAGES'
