### ISSUE TITLE
Is there a way to constrain parameters for ulam?

### ISSUE THREAD

**Issue by schwa021** [rmcelreath/rethinking#175]
I want to constrain some parameters (e.g. half-normal). I tried using the map2stan syntax for ulam, but ulam doesn't seem to use "constraints" parameter (see example below). Is there a way to do this in ulam?

mod1 <-
  ulam(
    modlist,
    data = dlist,
    chains = 4,
    iter = 2000,
    cores = 4,
    log_lik = TRUE,
    control = list(adapt_delta=0.98),
    constraints=list(ymax="lower=0")
  )

Returns: "Error: passing unknown arguments: constraints"

**Comment by rmcelreath** [comment]
I believe it does recognize constraints. See https://github.com/rmcelreath/rethinking/commit/d736033483e6443f0e35256dba22ba25d46a6284

**Comment by schwa021** [comment]
Hi Richard,

1. Thanks for the quick reply. And, of course, for the package, book, and youtube course!
2. It looks like I was running 1.87. I'm surprised, because I thought I had updated.
3. In any case - you are correct (not surprisingly) - it works like a charm in 1.88!!!!

Thanks again.
