### ISSUE TITLE
Could not find function "dens"

### ISSUE THREAD

**Issue by evgenyneu** [rmcelreath/rethinking#177]
After executing Rcode 2.8 and 2.9 from Statistical Rethinking 2 I get the following error:

> Error in dens(p, xlim = c(0, 1)) : could not find function "dens"

### The code I used

```
n_samples <- 1000
p <- rep( NA , n_samples )
p[1] <- 0.5
W <- 6
L <- 3
for ( i in 2:n_samples ) {
    p_new <- rnorm( 1 , p[i-1] , 0.1 )
    if ( p_new < 0 ) p_new <- abs( p_new )
    if ( p_new > 1 ) p_new <- 2 - p_new
    q0 <- dbinom( W , W+L , p[i-1] )
    q1 <- dbinom( W , W+L , p_new )
    p[i] <- ifelse( runif(1) < q1/q0 , p_new , p[i-1] )
}

dens( p , xlim=c(0,1) )
curve( dbeta( x , W+1 , L+1 ) , lty=2 , add=TRUE )
```

### Package version

```
> packageVersion("rethinking")
[1] ‘1.88’
```

**Comment by jamesbrownlow** [comment]
what version of R ?   3.6.1 seems to have fixed a number of these things

**Comment by rmcelreath** [comment]
Mysterious. My only advice is to go outside RStudio (if you use it), run R in the terminal, and reinstall rethinking. That has fixed some mysterious bugs like this for some users. But I really have no ideas in this case.

**Comment by evgenyneu** [comment]
Thanks. I'm so dumb, I forgot to load the library with `library(rethinking)`. :)
