### ISSUE TITLE
Accessing the Course Material

### ISSUE THREAD

**Issue by RoyiAvital** [rmcelreath/rethinking#18]
Hello,
Is there a way to access the course material (http://xcelab.net/rm/statistical-rethinking/)?

Thank You.

**Comment by torkar** [comment]
What material are you referring to in particular?

**Comment by RoyiAvital** [comment]
Well, 4 years after :-).

Was there a course with lecture slides or something like that in the past?
Just guessing...

**Comment by torkar** [comment]
Oh, Richard has put lots of material online (including the slides for his lectures and videos of the lectures): https://xcelab.net/rm/statistical-rethinking/

**Comment by RoyiAvital** [comment]
Probably this is it.
I guess when I opened the issue whose were not available on the page.

Thank You.
