### ISSUE TITLE
Issue installing rethinking package

### ISSUE THREAD

**Issue by JamesSteeleII** [rmcelreath/rethinking#182]
I've been having trouble installing the rethinking package to get started. Initially I was having issues with the updates to certain packages during the rethinking install so after looking at some prior messages I updated them all individually which seems to have solved that issue. Now however whenever I try to install from github I get the following:

```
> devtools::install_github("rmcelreath/rethinking", ref="Experimental")
Downloading GitHub repo rmcelreath/rethinking@Experimental
Error: Failed to install 'rethinking' from GitHub:
  Command not found @win/processx.c:977
```

Has anyone else encountered this and have any ideas on how to solve?

Thanks in advance!

**Comment by jamesbrownlow** [comment]
are you able to install the ordinary (not experimental) version?

**Comment by JamesSteeleII** [comment]
I get the same issue with both the ordinary and experimental versions.

**Comment by jamesbrownlow** [comment]
are you using R-3.6.1?   
Also have you tried using pystan in Python?

**Comment by JamesSteeleII** [comment]
Well, I think I may have figured out the issue... the problem was occurring on my networked laptop but I think there were some issues in updating R to 3.6.1 whilst I was off the network. Different files/folders in different locations. I've managed to get the package installed on my university PC. I've two positions though and haven't been to the office with my laptop to get on the network and try again. Tomorrow I will though and will try uninstalling R and reinstalling it. Will report back if that works!

**Comment by JamesSteeleII** [comment]
All sorted - got it installed now on both desktop and laptop.

Laptop worked after managing to get everything uninstalled and reinstalled.
