### ISSUE TITLE
No template for distribution '&' using ulam.  map2stan still works.

### ISSUE THREAD

**Issue by rer98** [rmcelreath/rethinking#183]
For question 8H3 in Chapter 9, I try to run the code in the book (page 300 of the 2nd edition draft from August 2019) using the ulam() function instead of map2stan():
```
m5.8u2 <- ulam(
            alist(
                height ~ dnorm( mu , sigma ) ,
                mu <- a + bl*leg_left + br*leg_right ,
                a ~ dnorm( 10 , 100 ) ,
                bl ~ dnorm( 2 , 10 ) ,
                br ~ dnorm( 2 , 10 ) & T[0,] ,
                sigma ~ dcauchy( 0 , 1 )
            ) ,
            data=d, chains=4, cores=4, start=list(a=10,bl=0,br=0,sigma=1) )
```

The result is the following error message:

> 
> Error in get_dist_template(the_dist[1]): No template for distribution '&'
> Traceback:
> 
> 1. ulam(alist(height ~ dnorm(mu, sigma), mu <- a + bl * leg_left + 
>  .     br * leg_right, a ~ dnorm(10, 100), bl ~ dnorm(2, 10), br ~ 
>  .     dnorm(2, 10) & T[0, ], sigma ~ dcauchy(0, 1)), data = d, 
>  .     chains = 4, cores = 4, start = list(a = 10, bl = 0, br = 0, 
>  .         sigma = 1))
> 2. get_dist_template(the_dist[1])
> 3. stop(concat("No template for distribution '", the_dist, "'"))

The current way around this is, obviously, to still use map2stan, but thought you should be aware of this issue.

Best wishes,

Ross

**Comment by rmcelreath** [comment]
Sorry about that. The homework questions aren't revised yet. 

ulam() doesn't use the T[,] notation. At least not yet. You can apply a custom constraint or use the half_normal template.
