### ISSUE TITLE
Code 12.26 - 12.28 and Figure 12.6

### ISSUE THREAD

**Issue by rer98** [rmcelreath/rethinking#184]
Hi Richard,

I find that your code boxes 12.26 - 12.28 in the 2nd edition of the book (version 22nd September and earlier) don't produce the top row of Figure 12.6 as implied.

There is some inconsistency in that code box 12.28 requires the definition of 'post$cutpoints', however the preceding code does not define 'post'.  The only time that the model has been used to generate the posterior distribution is with the line `phi <- link( m12.6 , data=pdat )$phi` in box 12.27.  Indeed, I see that the link() function only outputs the 'phi' and 'BI' variables as defined in box 12.24; there is no 'cutpoints' output anywhere.  Is there an in-built function that produces the cutpoints that are simultaneously sampled with the phi?  Please let me know if there is!

(As an aside, I also notice that earlier in the book in box 11.16, you use the 'link_ulam' function for models sampled by ulam, instead of the 'link'.  I don't know whether box 11.16 or later boxes like 12.27 need to be changed in the book for consistency?).

The way I get around the unavailability of posterior samples of cutpoints is to use extract.samples and manually calculate the phi, as below.  However this necessitates using quap instead of ulam as extract.samples creates the following error message:

```
Error in .local(object, ...): unused argument (data = pdat)
Traceback:

1. extract.samples(m12.6, data = pdat)
2. extract.samples(m12.6, data = pdat)
3. rstan::extract(object@stanfit, ...)
4. rstan::extract(object@stanfit, ...)

```
I'm not sure if there is a ulam-specific version of the extract.samples() method.  Please let me know if there is!

Here's the working code using quap:
```
m12.6q <- quap(
            alist(    
                R ~ dordlogit( phi , c(a1,a2,a3,a4,a5,a6) ),
                phi <- bA*A + bC*C + BI*I ,
                BI <- bI + bIA*A + bIC*C ,
                c(bA,bI,bC,bIA,bIC) ~ dnorm( 0 , 0.5 ),
#                 cutpoints ~ dnorm( 0 , 1.5 )
                c(a1,a2,a3,a4,a5,a6) ~ dnorm( 0 , 1.5 )
                ) ,
                data=dat
                , start=list(a1=-2,a2=-1,a3=0,a4=1,a5=2,a6=2.5) 
)

kA <- 0
# value for action

kC <- 0
# value for contact

kI <- 0:1
# values of intention to calculate over

pdat <- data.frame(A=kA,C=kC,I=kI)

post <- extract.samples( m12.6q , data=pdat )

A <- pdat['A']
C <- pdat['C']
I <- pdat['I']

phi_hat = matrix(nrow=length(post$bA), ncol=2)
for (i in 1:2) phi_hat[,i] <- post$bA*A[i,] + post$bC*C[i,] + post$bI*I[i,] + post$bIA*A[i,] + post$bIC*C[i,]

plot( NULL , type="n" , xlab="intention" , ylab="probability" ,
xlim=c(0,1) , ylim=c(0,1) , xaxp=c(0,1,1) , yaxp=c(0,1,2) )
for ( s in 1:50 ) {
    cutpoints <- c(post$a1[s], post$a2[s], post$a3[s], post$a4[s], post$a5[s], post$a6[s] )
    pk <- pordlogit( 1:6 , phi_hat[s,] , cutpoints )
    for ( i in 1:6 ) lines( kI , pk[,i] , col=col.alpha("black",0.1) )
}
```

I'd appreciate it if you could post me the working code to produce Figure 12.6 from an ulam version of the model, assuming it differs from that in the book.  

Thanks again for your excellent book!

Best wishes,

Ross

**Comment by rmcelreath** [comment]
Thanks, Ross. So it seems like all that is missing is `post <- extract.samples( m12.6 )`. This was apparently already there in my local branch. I'll make sure it gets merged into release.
