### ISSUE TITLE
Running sim() with an ulam() object is not working when using a student's t distribution

### ISSUE THREAD

**Issue by fsdias** [rmcelreath/rethinking#187]
R 3.6.1/rethinking 1.9/ Ubuntu 18.04

Data preparation:

```
library(rethinking)
data(Howell1)
d <- Howell1
d2 <- d[ d$age >= 18 , ]
```

With a normal distribution the code works:

```
t1 <- ulam(
  alist(
    height ~ normal( mu , sigma ) ,
    mu <- a + b*weight ,
    a ~ normal( 178 , 20 ) ,
    b ~ normal( 0 , 1 ) ,
    sigma ~ cauchy( 0 , 2)
  ) ,warmup=1000,iter=2000,chains=2,cores=2,
  data=d2 )

sim1<-sim(t1)
```

but when I change it to a t-distribution it returns an error

```
t2 <- ulam(
  alist(
    height ~ student_t( nu,mu , sigma ) ,
    mu <- a + b*weight ,
    a ~ normal( 178 , 20 ) ,
    b ~ normal( 0 , 1 ) ,
    sigma ~ cauchy( 0 , 2),
    nu~gamma(2, 0.1)
  ) ,warmup=1000,iter=2000,chains=2,cores=2,
  data=d2 )

sim2<-sim(t2)

Error in rt(352, nu, mu, sigma) : unused argument (sigma)
```
Is this a bug, a missing feature or am I doing something wrong?

Thanks

**Comment by rmcelreath** [comment]
Looks like R's rt() doesn't take mu and sigma parameters, it just simulates a standardized student distribution. I'll have to write a new R function. Will add it to my list.

Thanks.

**Comment by rmcelreath** [comment]
Just pushed a fix. https://github.com/rmcelreath/rethinking/commit/32bf0d8901c5e429d496dcdf3e5748e555f84af5

If you have more trouble, please let me know.

**Comment by fsdias** [comment]
It's working, thank you for the quick fix!
