### ISSUE TITLE
Multivariate linear model with varying intercepts and slopes - Rho[1,1] = NA. Why?

### ISSUE THREAD

**Issue by fsdias** [rmcelreath/rethinking#188]
Hi,
I have a question that may be more suitable for STAN's forum. If you think that is the case I will close this issue and ask it there.

I am trying to fit a multivariate linear model with varying intercepts and slopes. For a while I've been puzzled by the fact that Rho[1,1] is NA. I thought that there might be something wrong with my approach/code/data, but I just found a similar example in the most recent draft for the 2nd edition of Statistical Rethinking. I searched the draft but could not find an explanation for this. Why is Rho[1,1] = NA? Should I be worried? 

Here's the example I found in the book.

Data
```
set.seed(73)
N <- 500
U_sim <- rnorm( N )
Q_sim <- sample( 1:4 , size=N , replace=TRUE )
E_sim <- rnorm( N , U_sim + Q_sim )
W_sim <- rnorm( N , U_sim + 0*E_sim )
dat_sim <- list(
  W=standardize(W_sim) ,
  E=standardize(E_sim) ,
  Q=standardize(Q_sim) )
```
ulam() code
```
m14.5 <- ulam(
  alist(
    c(W,E)~multi_normal(c(muW,muE),Rho,Sigma),
    muW<-aW+bEW*E,
    muE <- aE + bQE*Q,
    c(aW,aE)~normal(0,0.2),
    c(bEW,bQE)~normal(0,0.5),
    Rho ~ lkj_corr(2),
    Sigma ~ exponential(1)
  ),data=dat_sim,chains=4,cores=4)
```
```
precis(m14.5,depth=3)
               mean   sd  5.5% 94.5% n_eff Rhat
aE           0.00 0.04 -0.06  0.06  1635 1.00
aW          0.00 0.04 -0.07  0.07  1548 1.00
bQE        0.59 0.03  0.54  0.64   1245 1.00
bEW        -0.05 0.07 -0.16  0.07   659 1.01
Rho[1,1]  1.00 0.00  1.00  1.00   NaN  NaN
Rho[1,2]  0.54 0.05  0.46  0.62    697 1.00
Rho[2,1]  0.54 0.05  0.46  0.62   697 1.00
Rho[2,2]  1.00 0.00  1.00  1.00   2009 1.00
Sigma[1]  1.02 0.05  0.96  1.10    788 1.00
Sigma[2]  0.81 0.03  0.77  0.85  1709 1.00
```

**Comment by rmcelreath** [comment]
This has something to do with how Stan computes n_eff and Rhat. Never been clear to me why Rho[1,1] gets NaN while Rho[2,2] does not, since both are invariant (always 1).

Anyway, Stan developers could surely explain it.

**Comment by riverscale-proj** [comment]
That's a big relief, thank you!

**Comment by fsdias** [comment]
That's a relief! Thank you.
