### ISSUE TITLE
Failure to replicate Figure 13.4/m13.1

### ISSUE THREAD

**Issue by bugcounting** [rmcelreath/rethinking#189]
Running the same code as the book, I get a fitted model `m13.1` that
seems to be substantially different from the one shown in the
book. While I cannot be completely sure, the differences seem quite
larger than what may be justified by simulation variance alone. This
is the only example of the many I've tried to replicate in the book
where the difference between my simulation and the book's is so
marked and "qualitative".

Specifically, running R code 13.13 gives the density plot [f13.4.pdf](https://github.com/rmcelreath/rethinking/files/3685082/f13.4.pdf),
which should be qualitatively similar to the blue plot in Figure 13.4
in the book. The plot shown in the book peaks to the left of `-0.5`,
consistently with the fact that the "real" correlation (used in the
simulation process that generated the data) is `-0.7`; also, its
probability is overwhelmingly on negative values, with only a short
tail that covers some positive values. In contrast, the density plot I
get (`f13.4.pdf`) is less strongly skewed, peaks to the right of
`-0.5`, and has a long tail that goes all the way to value `+1.0`.

Note that even if I switch to using a much stronger prior, I still do
not get a shape that is qualitatively similar to the books. For
example, [f13.4-strongprior.pdf](https://github.com/rmcelreath/rethinking/files/3685084/f13.4-strongprior.pdf) is the density plot I get when using
`dlkjcorr(6)` as a prior for `Rho`.

My simulations have been run using R 3.6.1 (2019-07-05), `rethinking`
version 1.59, `rstan` version 2.19.2, GitRev: 2e1f913d3ca3, and Stan
version 2.19.1 on a Linux (Ubuntu) box.

Plot [f13.4-b.pdf](https://github.com/rmcelreath/rethinking/files/3685083/f13.4-b.pdf) shows the plot obtained with the book's code run on
a different system, using R 3.6.1, `rethinking` latest version in the
development branch, `rstan` version 2.19.2 on a MacBook Pro. Plot
`f13.4-b.pdf` seems compatible with `f13.4.pdf`, and hence also quite
different from the book's.

If useful to better understand what's going on, I can provide more
data about my simulation(s).

**Comment by torkar** [comment]
Also, @rmcelreath , this might be a similar issue (something with the sampling that has changed, i.e., Stan?). For the **solution** for **6H1** it differs now compared to last year. Last year I got the same answer as you did, but now I get this when running the code.
![image](https://user-images.githubusercontent.com/22315/66154679-51f61580-e61e-11e9-8280-3127729f3ab4.png)

I'm using R 3.6.1, rethinking latest version in the development branch, rstan version 2.19.2 on a MacBook Pro.

**Comment by torkar** [comment]
I can, however, replicate the picture using `brms`:
![Rplot](https://user-images.githubusercontent.com/22315/66251703-540dc080-e753-11e9-8713-cf1947aa0cd0.png)

**Comment by torkar** [comment]
@bugcounting if I use `ulam` instead of `map2stan` (also with slightly different priors) it seems to work (from 2nd ed draft):

> m14.1 <- ulam(
>     alist(
>         wait ~ normal( mu , sigma ),
>         mu <- a_cafe[cafe] + b_cafe[cafe]*afternoon,
>         c(a_cafe,b_cafe)[cafe] ~ multi_normal( c(a,b) , Rho , sigma_cafe ),
>         a ~ normal(5,2),
>         b ~ normal(-1,0.5),
>         sigma_cafe ~ exponential(1),
>         sigma ~ exponential(1),
>         Rho ~ lkj_corr(2)
>     ) , data=d , chains=4 , cores=4 )
![Rplot](https://user-images.githubusercontent.com/22315/66255352-b4682680-e782-11e9-88f5-007d8afdc304.png)

**Comment by flaviobarros** [comment]
I have the same issue. It's not possible to reproduce models on chapter 13, even with ulam. 

`## Data
dat <- list(
  S = d$surv,
  N = d$density,
  tank = d$tank )

# approximate posterior
m13.1 <- ulam(
  alist(
    S ~ dbinom( N , p ) ,
    logit(p) <- a[tank] ,
    a[tank] ~ dnorm( 0 , 1.5 )
  ), data=dat , chains=1 , log_lik=TRUE )`

I got the following error:

`Compiling Stan program...
Running MCMC with 1 chain, with 1 thread(s) per chain...

Chain 1 Must use algorithm=fixed_param for model that has no parameters. 
Warning: Chain 1 finished unexpectedly!

Error in rstan::read_stan_csv(cmdstanfit$output_files()) : 
  csvfiles does not contain any CSV file name
Além disso: Warning message:
No chains finished successfully. Unable to retrieve the fit.`

**Comment by rmcelreath** [comment]
This issue is old, refers to 1st edition, and I'm closing it. The issue posted just above is nothing like the OP.
