### ISSUE TITLE
Problem Installing Packages

### ISSUE THREAD

**Issue by profredowl** [rmcelreath/rethinking#19]
Would you please advise how I can address the following installation error?

> install.packages(c("coda","mvtnorm","devtools"))

  There is a binary version available but the source version is later:
Error in install.packages : 8 arguments passed to .Internal(format) which requires 9
>

I am running current version of R (3.2.3) on 64-bit Windows 10.

I have installed Rtools33.exe and verified that all is OK in R with the commands:
Sys.getenv("PATH") #Check Rtools installation and path
system('g++ -v')
system('where make')

I have also run the following commands in R:
install.packages("loo") ## per https://github.com/rmcelreath/rethinking/issues/13
install.packages("rstan", dependencies = TRUE)
library(rstan) # observe startup messages

Any advice will be appreciated.

Red Owl (yes, my real name)

**Comment by profredowl** [comment]
I have narrowed the problem to mvtnorm, which was updated to v 1.0-4 on 1/19/16.

I have a previous installation of mvtnorm v 1.0-3 in my R, but the installing the rethinking package throws the following error since v 1.0-4 cannot be installed/updated:

* installing *source* package 'rethinking' ...
** R
** data
** inst
** preparing package for lazy loading
Creating a generic function for 'coef' from package 'stats' in package 'rethinking'
Creating a generic function for 'vcov' from package 'stats' in package 'rethinking'
Creating a generic function for 'nobs' from package 'stats' in package 'rethinking'
Creating a generic function for 'logLik' from package 'stats' in package 'rethinking'
Creating a generic function for 'deviance' from package 'stats' in package 'rethinking'
Creating a generic function for 'AIC' from package 'stats' in package 'rethinking'
Creating a generic function for 'pairs' from package 'graphics' in package 'rethinking'
** help
*** installing help indices
** building package indices
Error in format.default(x, width = width, justify = if (flag == "-") "left" else "right") : 
  8 arguments passed to .Internal(format) which requires 9
ERROR: installing package indices failed
* removing 'q:/R/R-3.2.3/library/rethinking'
Error: Command failed (1)

Without the rethinking package and the ability to do the exercises, the pedagogical logic of the Rethinking book fails, since the exercises cannot be completed.  I assume others trying to do this after 1/19/16 must be having same problem due to mvtnorm.

Please help or advise if you can.

Thanks.

Red Owl (yes, my real name)

**Comment by rasmusab** [comment]
Hmmm, this seems very similar to this bug: https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16411 . But according to that discussion (scroll to the bottom) it was only present in R 3.2.2 , which you don't have, and should be fixed in R 3.2.3....

**Comment by profredowl** [comment]
Thanks, rasmusab, for taking the time to help me with this.  Problem is fixed now with your help.

I had uninstalled and reinstalled Rtools33.exe and all of the relevant packages, but I had not questioned my installation of R 3.2.3, because it had seemed to install correctly.

After reading the bug report you linked, I uninstalled R 3.2.3 and then reinstalled it.  That fixed the problem.

Red Owl (yes, my real name)

**Comment by rasmusab** [comment]
Yeah, it seems like it was a pretty short-lived bug in base R... Great that it works now! :)

**Comment by maksports** [comment]
I have R 3.4.0 and get the following failure when executing the R code 0.5 in the book. Any help appreciated. 
Martin Keane

library(devtools)
> devtools::install_github("rmcelreath/rethinking")
Downloading GitHub repo rmcelreath/rethinking@master
from URL https://api.github.com/repos/rmcelreath/rethinking/zipball/master
Installing rethinking
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/mak/AppData/Local/Temp/RtmpgP1ter/devtools2e107a7c3a69/rmcelreath-rethinking-a309712"  \
  --library="C:/Users/mak/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'rethinking' ...
** R
** data
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'matrixStats'
ERROR: lazy loading failed for package 'rethinking'
* removing 'C:/Users/mak/Documents/R/win-library/3.4/rethinking'
Error: Command failed (1)

**Comment by cmpgervais** [comment]
Appears to be an issue with R 3.4.2 maybe? I recently had to setup a new working environment for a colleague and pulled down 3.4.2. Experienced issues for virtually every package, rolled back to 3.4.1 and no issues since!

**Comment by JohnsonBrent** [comment]
@maksports (and anyone else stumbling across this thread)... What worked for me with R 3.4.3 was to install matrixStats independent of rethinking as in, `install.packages("matrixStats")`. And if that fails (and if you're running this on Windows), try `install.packages("matrixStats",type="win.binary")`.
