### ISSUE TITLE
passing a function to stan through map2stan ?

### ISSUE THREAD

**Issue by ppernot** [rmcelreath/rethinking#20]
Hi,

is there any way to pass a function defining a complex non-linear data model
through map2stan ???

My hand built .stan file would look like this:
functions {
  vector viscosity(vector x, real eps, real sig) {
   ... function body 
 }
}
model {
  y ~ normal(viscosity(x,eps,sig), sigma);
}

**Comment by rmcelreath** [comment]
Not yet. But that is actually on my to-do list. I think I have a way to do it pretty easily.

**Comment by ppernot** [comment]
Good to hear that!
Excellent package and book, by the way !!!
