### ISSUE TITLE
Feature request: `map2stan` option for caching fitted model

### ISSUE THREAD

**Issue by tmalsburg** [rmcelreath/rethinking#208]
I'd like `map2stan` to be able to cache a fitted model and to refit only on demand; basically something similar to brms' `file` parameter.

Background: I use literate programming for teaching materials, something like RMarkdown (org-mode), and I don't want to refit all models every time I export to PDF.  Org-mode has caching but I need something with finer granularity.  For instance, if I make a cosmetic change in a code chunk, the cached value for that chunk is invalidated and all models in that chunk are rerun when I export to PDF.  This happens all the time and costs me insane amounts of time.  The code chunks are displayed in my slides, so they should be as simple and clean as possible.  For this reason it would be good to be able to activate caching by default, so I don't have to do it for every model explicitly.

**Comment by rmcelreath** [comment]
I'll be happy to add this. I am not yet sure what's needed though. I do not use markdown reports and I do not use brms. If you could give me a pure Stan example, I could probably do it without much effort.

**Comment by tmalsburg** [comment]
Here's an example:

``` R
m8m1.1 <- map2stan(
  alist(
    log_gdp ~ dnorm(mu, sigma) ,
    mu     <- a + bR*rugged,
    a       ~ dnorm(0, 100),
    bR      ~ dnorm(0, 10),
    sigma   ~ dunif(0, 10)
  ),
  data = dd.trim,
  file = "m8m1.1")
```

The parameter `file` is either ‘NULL’ or a character string.  In the former case, it doesn't do anything.  In the latter case, the fitted model object is saved via `saveRDS` in a file named after the string supplied in `file`.  The `.rds` extension is added automatically.  If the file already exists, `map2stan` will load and return the saved model object instead of refitting the model.  As existing files won't be overwritten, you have to manually remove the file in order to refit and save the model under an existing file name. The file name is stored in the `map2stan` object for later usage.

So if the code above is run the first time, everything works as usual except that the model is additionally stored on disk.  If the code is run a second time, no model is fit but the old fit is returned.

Brms has this feature and it saves a ton of time when working with literate programming systems (RMarkdown, Knitr, Org Babel) and otherwise.

Hope this descriptions makes it clearer.

**Comment by rmcelreath** [comment]
I have a working prototype in `ulam`, which is replacing `map2stan` in 2nd edition. It uses `saveRDS` to working directory and `readRDS` to restore. Hopefully it has the intended behavior.

Example:
```
library(rethinking)
data(chimpanzees)
d <- list( 
    pulled_left = chimpanzees$pulled_left ,
    prosoc_left = chimpanzees$prosoc_left ,
    condition = as.integer( 2 - chimpanzees$condition ) ,
    actor = as.integer( chimpanzees$actor ) ,
    blockid = as.integer( chimpanzees$block )
)
m1 <- ulam(
    alist(
        pulled_left ~ bernoulli(theta),
        logit(theta) <- a + bp[condition]*prosoc_left  ,
        a ~ normal(0,4),
        bp[condition] ~ normal(0,1)
    ) , data=d , chains=4 , file="m1" )
```

**Comment by tmalsburg** [comment]
Thank you, Richard. It's the final week of the term, really busy.  I will test it soonish and report back.

**Comment by JohannesNE** [comment]
To make this more safe, it could check that the current function call matches @call in the loaded model. 
Otherwise either refit model or give a warning.

**Comment by tmalsburg** [comment]
Sorry, lost track of this.  I just tried your example above but get an error message:

```make cmd is
  make -f '/usr/lib/R/etc/Makeconf' -f '/usr/share/R/share/make/shlib.mk' CXX='$(CXX14) $(CXX14STD)' CXXFLAGS='$(CXX14FLAGS)' CXXPICFLAGS='$(CXX14PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX14LDFLAGS)' SHLIB_LD='$(SHLIB_CXX14LD)' SHLIB='file56f4758ab0e86.so' OBJECTS='file56f4758ab0e86.o'

make would use
if test  "zfile56f4758ab0e86.o" != "z"; then \
  echo g++ -std=gnu++14 -shared -L"/usr/lib/R/lib" -Wl,-Bsymbolic-functions -Wl,-z,relro -o file56f4758ab0e86.so file56f4758ab0e86.o  '/home/malsburg/R/x86_64-pc-linux-gnu-library/3.6/rstan/lib//libStanServices.a' -L'/home/malsburg/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/lib/' -lStanHeaders -L'/home/malsburg/R/x86_64-pc-linux-gnu-library/3.6/RcppParallel/lib/' -ltbb  -L"/usr/lib/R/lib" -lR; \
  g++ -std=gnu++14 -shared -L"/usr/lib/R/lib" -Wl,-Bsymbolic-functions -Wl,-z,relro -o file56f4758ab0e86.so file56f4758ab0e86.o  '/home/malsburg/R/x86_64-pc-linux-gnu-library/3.6/rstan/lib//libStanServices.a' -L'/home/malsburg/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/lib/' -lStanHeaders -L'/home/malsburg/R/x86_64-pc-linux-gnu-library/3.6/RcppParallel/lib/' -ltbb  -L"/usr/lib/R/lib" -lR; \
fi
Error in compileCode(f, code, language = language, verbose = verbose) : 
    650 |   return internal::first_aligned<int(unpacket_traits<DefaultPacketType>::alignment),Derived>(m);      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/bin/ld: /home/malsburg/R/x86_64-pc-linux-gnu-library/3.6/rstan/lib//libStanServices.a(stan_fit.o): relocation R_X86_64_PC32 against undefined hidden symbol `_ZTCN5boost10wrapexceptINS_4math14rounding_errorEEE0_NS_16exception_detail10clone_implINS4_19error_info_injectorIS2_EEEE' can not be used when making a shared object/bin/ld: final link failed: bad valuecollect2: error: ld returned 1 exit statusmake: *** [/usr/share/R/share/make/shlib.mk:6: file56f4758ab0e86.so] Error 1
Error in sink(type = "output") : invalid connection
```

Probably unrelated to this feature because it also happens when I drop the `file` parameter.

Tested with fresh rethinking package (installed following your instructions) and with `R version 3.6.3 (2020-02-29)`.

Perhaps this problem is already known. Otherwise I can create a new issue.
