### ISSUE TITLE
Error installing rethinking package from Experimental branch

### ISSUE THREAD

**Issue by yr67** [rmcelreath/rethinking#210]
I am trying to install package as recommended devtools::install_github("rmcelreath/rethinking",ref="Experimental")

but get error 

* installing *source* package 'rethinking' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'rstan' was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package 'rethinking'
Execution halted
ERROR: lazy loading failed for package 'rethinking'
* removing 'C:/Users/Yuri/Documents/R/win-library/3.6/rethinking'
* restoring previous 'C:/Users/Yuri/Documents/R/win-library/3.6/rethinking'
Error: Failed to install 'rethinking' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Yuri/AppData/Local/Temp/Rtmpkju0li/file19981c41524c/rethinking_1.95.tar.gz’ had non-zero exit status

I reinstall rstan package and repeat, installation ended with the same error

**Comment by rmcelreath** [comment]
No idea, but the problem isn't rethinking. Is your R up to date?
