### ISSUE TITLE
1st edition of the book - solutions to the practice exercises?

### ISSUE THREAD

**Issue by mergrau** [rmcelreath/rethinking#211]
Hi, I haven´t been able to download the rethinking package (still revising and trying all the issues and solutions previously posted here about this, the problem seems to be first about the mtvnorm package and then to the inability to find the rethinking package on github), nor have I been able to find solutions to the practice exercises.

I understand this is due to my basic knowledge of R, which is getting very frustrating. The book (1st edition is the one I purchased) states in page 17 that the solutions to the exercises are available online, where would that be? At least I could work through this while I am blocked with the package installation. Sorry for the basic questions :( I am also new at GitHub.

Many thanks

**Comment by rmcelreath** [comment]
You can download the solutions guide (1st edition) here: http://xcelab.net/rmpubs/rethinking/rethinking_solutions_2.pdf

I don't know yet how to help with package installation. If you can copy error messages here, I might be of more help.

**Comment by mergrau** [comment]
Thank you so much for this swift helpful reply Prof. McElreath, that was really helpful.

For the problems with the installation, it goes smoothly during the installation of rstan, then when trying to download the package this is what I get:

> library(devtools)
Loading required package: usethis
Warning messages:
1: package ‘devtools’ was built under R version 3.5.3 
2: package ‘usethis’ was built under R version 3.5.3 
> devtools::install_github("rmcelreath/rethinking", ref="Experimental")
Downloading GitHub repo rmcelreath/rethinking@Experimental
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

# **so here, I click 1 and enter, and I get:**
rlang       (0.4.0     -> 0.4.4    ) [CRAN]
scales      (1.0.0     -> 1.1.0    ) [CRAN]
tibble      (2.0.1     -> 2.1.3    ) [CRAN]
plyr        (1.8.4     -> 1.8.5    ) [CRAN]
Rcpp        (1.0.0     -> 1.0.3    ) [CRAN]
R6          (2.4.0     -> 2.4.1    ) [CRAN]
fansi       (0.4.0     -> 0.4.1    ) [CRAN]
pillar      (1.3.1     -> 1.4.3    ) [CRAN]
pkgconfig   (2.0.2     -> 2.0.3    ) [CRAN]
assertthat  (0.2.0     -> 0.2.1    ) [CRAN]
glue        (1.3.0     -> 1.3.1    ) [CRAN]
colorspace  (1.4-0     -> 1.4-1    ) [CRAN]
vctrs       (0.2.0     -> 0.2.3    ) [CRAN]
stringi     (1.3.1     -> 1.4.6    ) [CRAN]
checkmate   (1.9.4     -> 2.0.0    ) [CRAN]
matrixStats (0.54.0    -> 0.55.0   ) [CRAN]
backports   (1.1.4     -> 1.1.5    ) [CRAN]
prettyunits (1.0.2     -> 1.1.1    ) [CRAN]
ps          (1.3.0     -> 1.3.2    ) [CRAN]
jsonlite    (1.6       -> 1.6.1    ) [CRAN]
curl        (3.3       -> 4.3      ) [CRAN]
StanHeaders (2.18.1-10 -> 2.19.2   ) [CRAN]
ggplot2     (NA        -> 3.2.1    ) [CRAN]
pkgbuild    (1.0.3     -> 1.0.6    ) [CRAN]
RcppEigen   (0.3.3.5.0 -> 0.3.3.7.0) [CRAN]
Installing 25 packages: rlang, scales, tibble, plyr, Rcpp, R6, fansi, pillar, pkgconfig, assertthat, glue, colorspace, vctrs, stringi, checkmate, matrixStats, backports, prettyunits, ps, jsonlite, curl, StanHeaders, ggplot2, pkgbuild, RcppEigen
Installing packages into ‘C:/Users/mergr/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/rlang_0.4.4.zip'
Content type 'application/zip' length 1110222 bytes (1.1 MB)
downloaded 1.1 MB


trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/scales_1.1.0.zip'
Content type 'application/zip' length 550341 bytes (537 KB)
downloaded 537 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/tibble_2.1.3.zip'
Content type 'application/zip' length 333984 bytes (326 KB)
downloaded 326 KB

[...] and final message:

package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'rethinking' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’


**If I try again withot trying to install any updates (without clickin 1), I get:**
Enter one or more numbers, or an empty line to skip updates:

Installing 2 packages: rlang, ggplot2
Installing packages into ‘C:/Users/mergr/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/rlang_0.4.4.zip'
Content type 'application/zip' length 1110222 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/ggplot2_3.2.1.zip'
Content type 'application/zip' length 3959188 bytes (3.8 MB)
downloaded 3.8 MB

package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'rethinking' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

**So, I tried remove.packages(rlang)** but I get 
Error in remove.packages : object 'rlang' not found

I know I must be doing something wrong, I just can't find what.

Thank you so much for your time and attention

**Comment by rmcelreath** [comment]
Whatever the trouble, it has nothing to do with my package, but rather with your R library. It's possibly corrupt, which is why you are having trouble with rlang. All I can suggest is to make sure you have the most recent version of R (3.6.3) and maybe to remove your library and reinstall everything.

If you search for the error `(converted from warning) cannot remove prior installation of package ‘rlang’` I imagine you'll find people have had this issue before.

**Comment by mergrau** [comment]
Thanks a lot for your time and your kind attention.

Best wishes,


Merce
