### ISSUE TITLE
Errors running MCMC Methods

### ISSUE THREAD

**Issue by mitchseeman** [rmcelreath/rethinking#213]
Working my way through book and have encountered problems running map2stan. The function runs fine on one machine, but on another they produced consistent errors. I have updated R, and reinstalled Rtools to ensure it is up to date. 

Running the code 

**library(rethinking)
data(chimpanzees)
d <- chimpanzees
d2 <- d
d2$recipient <- NULL

m10.3stan <- map2stan(m10.3, data = d2)**
 
produces 

"
Error in sink(type = "output") : invalid connection
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.3/bin/x64/R CMD SHLIB file2888530f7416.cpp 2> file2888530f7416.cpp.err.txt' had status 1
Error in map2stan(m10.3, data = d2) : 
  Something went wrong, when calling Stan. Check any debug messages for clues, detective.
invalid connection
"
The below post on the stan website seems to describe the same issue but I cannot interpret what it means to change the "compilation arguments".

https://discourse.mc-stan.org/t/error-in-sink-type-output-invalid-connection-in-map2stan-in-windows-10/8887/6

**Comment by rmcelreath** [comment]
The problem is not to do with my package, but with your compiler settings, as you seem to have discovered.

I cannot help with Windows compiler settings. I do not use Windows. On a Unix system, you would edit ~/.R/Makevars.

You should ask on the Stan forum.
