### ISSUE TITLE
Replicating Figure 12.3 (Section 12.2.5 - First edition)

### ISSUE THREAD

**Issue by emanjavacas** [rmcelreath/rethinking#218]
I've noticed that the code producing the plot that compares error of the partial pooling and the no-pooling approach per pond sample size was not giving the same result. It might be an issue with R versioning, but I am leaving this here in case it helps somebody.

The issue seems to be with this line:

```
ni <- as.integer( rep( c(5,10,25,35) , each=15 ) )
```
which produces

```
5 . 10 . 25 . 35 . 5 . 10 ...
```

However, to replicate the plot we need to repeat proportions in this manner:

```
5 . 5 . 5 . ... 10 . 10 . 10 . ...
```

This can be done with:

```
ni <- as.integer(rep(c(5, 10, 25, 35), c(15,15,15,15)))
```

**Comment by torkar** [comment]
Both approaches produce exactly the same results for me.

**Comment by emanjavacas** [comment]
Closing this
