### ISSUE TITLE
Consider making dagitty a suggested dependency?

### ISSUE THREAD

**Issue by khughitt** [rmcelreath/rethinking#235]
Dagitty depends on [v8](https://cran.r-project.org/web/packages/V8/index.html), which can be a pretty big pain to install on some OS's.

Since it seems like much of the functionality in `rethinking` is not dependent on that, would it perhaps make sense to make dagitty a "suggested" dependency?

This way users can still make use of the rest of the functionality of the library, even if they are unable to build v8.

To avoid confusion, one could also perhaps do a quick check whenever a function that _does_ depend on dagitty is called, and print a message to the user letting them know about the requirement, if it is not already installed.

**Comment by HaoZeke** [comment]
:+1: for this. v8 is a major pain on ArchLinux. Ended up using [nix just for this instead](https://rgoswami.me/posts/nix-r-devtools/).

**Comment by khughitt** [comment]
@HaoZeke If you haven't already tried it, I would recommend checking out the [v8-r AUR package](https://aur.archlinux.org/packages/v8-r/); it tends to compile more successfully than the base v8 package for me.

**Comment by rmcelreath** [comment]
The Experimental branch labels dagitty as recommended. See if that addresses the problem. https://github.com/rmcelreath/rethinking/blob/Experimental/DESCRIPTION#L10

**Comment by khughitt** [comment]
I just tested the branch, and it works great -- thanks for making the change! Closing the issue.
