### ISSUE TITLE
[Help] Non-centered parameterization of multinormal

### ISSUE THREAD

**Issue by zhengchencai** [rmcelreath/rethinking#240]
Hi there,

I was trying to reparameterize the multinormal between intercept and slope in homework 9 because there are some divergent transitions

c(a,b)[did] ~ multi_normal( c(abar,bbar) , Rho , Sigma ),

It seems that there was a function "dmvnormNC" for this purpose, but I guess it's not in the current version. Could you please give some hint for this reparameterization? I've look Stan user guild there is an example of non-centered parameterization of multinormal but I'm not familiar with the way Stan model. I'm still relying on the rethinking package.

Thanks,
Zhengchen

**Comment by rmcelreath** [comment]
https://github.com/rmcelreath/rethinking#multilevel-model-formulas

**Comment by zhengchencai** [comment]
Thanks for the help. I've tried the example in the readme file and it worked. So then I went one more step further by adding measurement error in the model like in Chapter15. To be short, the only difference is this little [i] 

logit(p) <- v_mu[1]+v[did,1] + (v_mu[2]+v[did,2])*predictor[i]

however, I got error saying "Scale parameter has dimension = 2, expecting dimension = 40 a function was called with arguments of different scalar, array, vector, or matrix types, and they were not consistently sized;  all arguments must be scalars or multidimensional values of the same shape."  40 is the nrow of the data. What I don't understand is that if I do centered multi-normal such as 
logit(p) <- v[dept,1] + v[dept,2]*predictor[i],
vector[2]:v[dept] ~ multi_normal( v_mu , Rho , sigma ), it will pass through with the [i] 

Only non-centered version end up with error. If I take out [i] non-centered version will also work. 

To summary, non-centered version with [i] after the predictor for encouting measurement error did not work.  centered version with/without [i] works

Could you please help? Thanks a lot. The following is the whole code. I was tring to study the difference of pre-/post- treatment effect
###########################################################
m1.3 <- ulam(
  alist(
    post_obs ~ normal(post_true, post_se),
    vector[N_spp]:post_true ~ normal(post_bar, sigma),
    post_bar <- v_mu[1]+ v[intid,1] + (v_mu[2] + v[intid,2])*pre_true[i],
    pre_obs ~ normal(pre_true, pre_se),
    vector[N_spp]:pre_true ~ normal(1.5, 1),    
    matrix[intid,2]: v <- t(diag_pre_multiply( sigma , L_Rho ) * z),
    matrix[2,intid]: z ~ normal( 0 , 1 ),
    vector[2]: v_mu[[1]] ~ normal(0,1),
    vector[2]: v_mu[[2]] ~ normal(0,1),
    vector[2]: sigma ~ exponential(1),
    cholesky_factor_corr[2]: L_Rho ~ lkj_corr_cholesky( 2 )
  ), data = dat_list, start=list( post_true=dat_list$post_obs , pre_true=dat_list$pre_obs ),
  chains = 4, cores = 4, iter = 4000, log_lik = TRUE
)
