### ISSUE TITLE
Error in pars[[i]] : subscript out of bounds in quap

### ISSUE THREAD

**Issue by bakaburg1** [rmcelreath/rethinking#241]
Hello, I'm trying to fit a very simple model to estimate the prevalence of disease as described here https://www.ecdc.europa.eu/sites/default/files/documents/Methodology-estimating-point-prevalence%20-SARS-CoV-2-infection-pooled-RT-PCR-testing.pdf on page 6.
 
Here's my code:

```
quap(alist(
    p ~ dbeta(.3, .3),
    p_test ~  1 - dbinom(0, s, p),
    k ~ dbinom(w, p_test)
), data = list(s = 10, k = 30, w = 200))
```
but I receive the error:
`Error in pars[[i]] : subscript out of bounds in quap`

What am I doing wrong?

Thank you very much,
Angelo D'Ambrosio

**Comment by rmcelreath** [comment]
quap models are parsed from the top, so you need to reverse the order. This seems to run:
```
library(rethinking)
m0 <- quap(alist(
    k ~ dbinom(w, p_test),
    p_test <-  1 - dbinom(0, s, p),
    p ~ dbeta(.3, .3)
), data = list(s = 10, k = 30, w = 200))
```
Also works in ulam:
```
m1 <- ulam(
    alist(
        k ~ dbinom(w , p_test),
        real[1]:p_test <- 1 - exp(binomial_lpmf(0|s,p)),
        p ~ dbeta(0.3,0.3)
    ),
    data=list(s = 10, k = 30, w = 200) , sample=TRUE )
```

**Comment by bakaburg1** [comment]
Thanks! I always thought about these models going from priors to the data. It confuses me that the statements at the top use parameters defined below.
