### ISSUE TITLE
Persistent installation error with rethinking 

### ISSUE THREAD

**Issue by dwanneruchi** [rmcelreath/rethinking#242]
I have already done through and uninstalled R, RStudio and Rtools. I am now working with: R 4.0.1, RStudio 1.3+, Rtools 4.0. 

Here are my steps: 

- I have successfully installed & tested rstan. 

- I have successfully installed coda, mvtnorm, devtools, loo, dagitty.

However, when I get down to this I get an error:
```R
devtools::install_github("rmcelreath/rethinking")
```

Error output:
```
> devtools::install_github("rmcelreath/rethinking")
Downloading GitHub repo rmcelreath/rethinking@master
   The system cannot find the path specified.
√  checking for file 'C:\Users\David\AppData\Local\Temp\RtmpcplnmA\remotes1c285c203b13\rmcelreath-rethinking-d0978c7/DESCRIPTION' ...
-  preparing 'rethinking': (537ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'rethinking_2.01.tar.gz' (429ms)
   
Error: Failed to install 'rethinking' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr:
E> The system cannot find the path specified.
E> * checking for file 'C:\Users\David\AppData\Local\Temp\RtmpcplnmA\remotes1c285c203b13\rmcelreath-rethinking-d0978c7/DESCRIPTION' ... OK
E> * preparing 'rethinking':
E> * checking DESCRIPTION meta-information ... OK
E> * checking for LF line-endings in source and make files and shell scripts
E> * checking for empty or unneeded directories
E> * looking to see if a 'data/datalist' file should be added
E> * building 'rethinking_2.01.tar.gz'
E> 
```

I have tried this numerous times with the same end result of failing to install from Github. Any recommendations would be greatly appreciated!

**Comment by rmcelreath** [comment]
Sorry, no idea. These errors always occur with Windows, and sometimes they are the result of file/folder permission problems. People have fixed the issue by completely removing their R installation/library and reinstalling everything. But I don't know if that would be any help in this instance.

**Comment by dwanneruchi** [comment]
@rmcelreath thanks for the response! What I ended up doing was downloading the zip and using the `install_local()` command which seems to work (I have only tried a few snippets from chapter 4). 

Hopefully that resolves it so I will close this. Thanks for putting together such an amazing book, really enjoying this!
