### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by mcooganj** [rmcelreath/rethinking#243]
I get the following error when i try to install the `rethinking` package using devtools. 
```

devtools::install_github("rmcelreath/rethinking")
Downloading GitHub repo rmcelreath/rethinking@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/rmcelreath/rethinking/tarball/master'
```
I'm using R 3.5.3 (MRAN)

**Comment by rmcelreath** [comment]
This looks like your computer is blocked from accessing github. Can you download the tarball and install from local? https://github.com/rmcelreath/rethinking/releases/tag/2.0.1

**Comment by mcooganj** [comment]
it did look like that, but my computer was able to access github via other means.  in the end installing R 4.0.2 and updating packages meant that everything was smooth.
