### ISSUE TITLE
Differing errors by groups throws compilation error

### ISSUE THREAD

**Issue by jebyrnes** [rmcelreath/rethinking#25]
I've been working with a collaborator who has a model build in STAN, but we'd like to translate it to rethinking as it's so much more accessible to the rest of our collaborators on the project. An odd feature of the model is that each Study (this is a meta-analysis - although I can think of other models this should be true for) has it's own residual error. So, in our model, our likelihood function is

      y ~ lognormal(y_loc, sd_e[Study])

for which our prior would be stated as

      sd_e[Study] ~ dcauchy(0,1) #prior for study level errors

However, before map2stan will run the model, I get the error

    Error in constr_list[[sigma_name]] : no such index at level 1

This wasn't super helpful in debugging, but I eventually tracked it down to the sd_e parameter, as when I took [Study] out of the residual, the model fit just fine.  I'm thinking that either this is the wrong way to use dcauchy or there is something wonkier here in terms of adding having multiple residual errors.  But given that normal distributions work just fine with a group structure, I cannot think of why this should fail.  Is there something in how the model is translated to STAN code?

**Comment by jebyrnes** [comment]
Reproducible example of error:

https://gist.github.com/jebyrnes/5eb17b9e6b78bbbe6012

The model works if `[group]` is removed from `sd_e`

**Comment by rmcelreath** [comment]
I posted a suggestion on the gist. Will repeat it here:
```
mod <- alist(
  #likelihood
  y ~ dnorm(y_loc, sd_lm), # likelihood
  
  #model
  sd_lm <- sd_e[group],
  y_loc <- a[group] + b[group]*x,
  
  #priors
  a[group] ~ dnorm(0,10),
  b[group] ~ dnorm(0,10),
  
  sd_e[group] ~ dcauchy(0,1) #prior for study level errors
)

fit <- map2stan(mod, data=my_df, constraints=list(sd_e="lower=0") , start=list(sd_e=rep(1,3)) )
```

**Comment by jebyrnes** [comment]
Works perfectly. I take it you cannot use grouping structure in the likelihood function?

**Comment by rmcelreath** [comment]
I think not, because the likelihoods end up vectorized in the Stan code. So they don't loop correctly over the index variable inside the grouping variable. The linear model form dodges this issue by building a vector from the indexed form and then vectorizing over it.

I suspect I could make the grouping variable work inside the likelihood, now that Stan supports R-style vector slicing. In the meantime, probably a good idea to add a check and warning.
