### ISSUE TITLE
installation in R 4

### ISSUE THREAD

**Issue by JuliaC42** [rmcelreath/rethinking#250]
my system is failing to install rethinking and I am getting this error:
Error: (converted from warning) package 'ggplot2' was built under R version 4.0.2
Execution halted
ERROR: lazy loading failed for package 'rethinking'
* removing '.../R/win-library/4.0/rethinking'

I had already installed rstan without a problem

**Comment by rmcelreath** [comment]
I suspect your version of R needs to be updated, because ggplot2 is telling you it was built on a version newer than the R on your system.

I believe there is a way to turn off this warning, in the devtools settings, or you can download the archive of rethinking to your machine and install local. That might bypass the warning.

**Comment by JuliaC42** [comment]
Thanks, I have now managed to install it.

NB I had this option
  There is a binary version available but the source version is later:
          binary source needs_compilation
backports  1.1.7  1.1.8              TRUE

rethinking wouldn't install with the source version, but worked with 1.1.7

**Comment by jdmoore7** [comment]
`package ‘rethinking’ is not available (for R version 4.0.2)` 

Uhoh, I'm much more of a python coder...should I retrograde to a 3.x release for compatibility?

**Comment by bbolker** [comment]
`rethinking` isn't on CRAN as far as I know.  Try `remotes::install_github("rmcelreath/rethinking")`

**Comment by jdmoore7** [comment]
@bbolker  - you are a saint; and quite timely too! Can't beat a 2min reply with a perfect answer :)

**Comment by AndreZular** [comment]
My system is failing to install rethinking. I am installing from this repository after the rstan installation: 

install.packages(c('coda','mvtnorm'))
options(repos=c(getOption('repos'),rethinking='http://xcelab.net/R'))
install.packages('rethinking',type='source')

I am getting this error:

Installing package into ‘C:/Users/Andre/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'http://xcelab.net/R/src/contrib/rethinking_2.01.tar.gz'
Content type 'application/x-tar' length 2241406 bytes (2.1 MB)
downloaded 2.1 MB

ERROR: dependency 'shape' is not available for package 'rethinking'
* removing 'C:/Users/Andre/Documents/R/win-library/4.0/rethinking'
Warning in install.packages :
  installation of package ‘rethinking’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Andre\AppData\Local\Temp\RtmpwX5w2j\downloaded_package

Any help? Thanks!

**Comment by rmcelreath** [comment]
You should install the 'shape' package.

**Comment by AndreZular** [comment]
Thanks!!!
