### ISSUE TITLE
Using MAP with custom likelihood functions

### ISSUE THREAD

**Issue by TylerBackman** [rmcelreath/rethinking#26]
From the documentation, it is not clear to me how map() will form it's function calls to the likelihood function, in a way that makes it straightforward to write a custom function. Could you clarify this in the documentation? 

It seems that map() expects the likelihood function to return log(p) values, and that it passes the option "log=true", and that it also passes the data itself as "x=". I can't find that this is described anywhere. My apologies if this is already explained somewhere, but I missed it.

It seems that perhaps this is standardized in R itself, but I wasn't able to find any official probability distribution API documentation, except this PDF on the cran list of distributions:

http://www.rmetrics.org/Meielisalp2009/Presentations/Scott.pdf
https://cran.r-project.org/web/views/Distributions.html

Some published likelihood functions I have seen don't seem to follow these guidelines, for example the Wallenius noncentral hypergeometric distribution provided by the biasedUrn package.

**Comment by rmcelreath** [comment]
Right, map assumes the classic R convention: density functions have the form dfoo(x,...,log=FALSE)

So map passes the "data" (could be parameter values) as x and adds log=TRUE to the argument list. In the event some density function doesn't obey that convention, I suppose writing a small wrapper function for it would work in most cases.
