### ISSUE TITLE
shade() still includes 'if (class(object) == ', which sometimes fails in R 4.0

### ISSUE THREAD

**Issue by jbullock35** [rmcelreath/rethinking#263]
In R 4.0, matrices have both class "array" and class "matrix." Testing whether `object` has a given class by using code like ` if (class(object) == [whatever])` thus leads to an error when `object` is a matrix: for example, `Error in if (class(object) == "formula") { : the condition has length > 1`. 

I know that you've already [fixed most problems arising from this change](https://twitter.com/rlmcelreath/status/1255163204751306752). But in v2.01 of the package, `shade()` still checks for classes with `if (class(object) == `, which produces errors. For example, in R code 4.61 of the first edition of the book, the `shade()` commands don't work when using R 4.0. I think that the same is true for R code 4.57 of the second edition, but I haven't tested that.

**Comment by rmcelreath** [comment]
I have no trouble with code 4.61 (1st edition), and all the class() class in shade() have [1] after them.

https://github.com/rmcelreath/rethinking/blob/master/R/plotting.r#L316

Are we referencing different versions?

**Comment by jbullock35** [comment]
Thank you. Yes, it looks as though we're referencing different versions. Sorry about that.

To elaborate: I'm using the latest release, v2.01 (d0978c7). In this release, `shade()` doesn't seem to have the [1] subscripts that you mentioned: 

https://github.com/rmcelreath/rethinking/blob/d0978c7f8b6329b94efa2014658d750ae12b1fa2/R/plotting.r#L316-L321

I hope that I haven't overlooked anything on this point. In any case, I can just install the package from the most recent commit. Thank you again, both for the book and for looking into this.

**Comment by rmcelreath** [comment]
Latest release is 2.11, so yes, you should just be able to update.

https://github.com/rmcelreath/rethinking/commit/89b3e63fe988f18022f0f45baadbd1e5fb451a6c

**Comment by jbullock35** [comment]
Please pardon my confusion -- but it looks as though the latest release is 2.01. Here is a screenshot:

![image](https://user-images.githubusercontent.com/4016787/88549288-b935e980-cfe5-11ea-98eb-3d3957230e1a.png)

One can still install v2.11, but not by following the installation instructions (`devtools::install_github("rmcelreath/rethinking")`). Did you mean to make v2.11 a release?

Again, my apologies if I'm missing something here.
