### ISSUE TITLE
`cmdstan = TRUE` in ulam+sim gives unordered predictions + smaller issues

### ISSUE THREAD

**Issue by DataDan01** [rmcelreath/rethinking#269]
Running: Windows 10, R 4.0.2, _rstan_ 2.21.2, _StanHeaders_ 2.21.0.6, _cmdstanr_ 0.1.3, and _cmdstan_ 2.24.1.

The code below details three issues:

1. Setting `cmdstan = TRUE` and using ulam+sim seems to give predictions that are not ordered in the way the data were input
2. Setting `cmdstan = TRUE` throws an error when you also set the `warmup` argument in an `ulam` call
3. `sim` ignores the `n` argument and always outputs 1000 posterior samples per observation (unrelated to cmdstan setting)

Copying code below using model 7.1 from the book as a baseline. No funky messages from either MCMC processes. `compare` using PSIS complains of k>0.5 but this doesn't matter here.

Can anybody else reproduce this across other platforms?

I really want to use `cmdstan` since it samples faster and has higher `n_eff`.

```
library(rethinking)

# Setting data up
sppnames <- c( "afarensis","africanus","habilis","boisei",
               "rudolfensis","ergaster","sapiens")
brainvolcc <- c( 438 , 452 , 612, 521, 752, 871, 1350 )
masskg <- c( 37.0 , 35.5 , 34.5 , 41.5 , 55.5 , 61.0 , 53.5 )
d <- data.frame( species=sppnames , brain=brainvolcc , mass=masskg )

d$mass_std <- (d$mass - mean(d$mass))/sd(d$mass)
d$brain_std <- d$brain / max(d$brain)

# Running model under rstan
m7.1_rstan <- ulam(
  alist(
    brain_std ~ dnorm( mu , exp(log_sigma) ),
    mu <- a + b*mass_std,
    a ~ dnorm( 0.5 , 1 ),
    b ~ dnorm( 0 , 10 ),
    log_sigma ~ dnorm( 0 , 1 )
  ), 
  data = d,
  warmup = 2e3,
  iter = 5e3,
  chains = 4,
  cores = 4,
  log_lik = TRUE
  )

# sim ignores `n` argument unless `post` samples are manually passed in
# Always gives back 1000 posterior samples per sim
dim(sim(m7.1_rstan, n = 0)) == dim(sim(m7.1_rstan, n = 1234))

sim_data <- data.frame(
  mass_std = seq(from = min(d$mass_std), to = max(d$mass_std), length.out = 20)
)

sim_rstan <- sim(fit = m7.1_rstan, 
                 data = sim_data,
                 post = extract.samples(
                   object = m7.1_rstan
                 ))

sim_data$rstan_mean_pred <- apply(sim_rstan, 2, mean)

# Running model under cmdstan
# Complains about `unused argument (warmup = 2000)`
m7.1_cmdstan <- ulam(
  alist(
    brain_std ~ dnorm( mu , exp(log_sigma) ),
    mu <- a + b*mass_std,
    a ~ dnorm( 0.5 , 1 ),
    b ~ dnorm( 0 , 10 ),
    log_sigma ~ dnorm( 0 , 1 )
  ), 
  data = d,
  # warmup = 2e3,
  iter = 5e3,
  chains = 4,
  cores = 4,
  log_lik = TRUE,
  cmdstan = TRUE
)

# Same model as rstan fit
compare(m7.1_rstan, m7.1_cmdstan, func = 'PSIS')
compare(m7.1_rstan, m7.1_cmdstan, func = 'WAIC')

# Same issue with sim's number of predictions
dim(sim(m7.1_cmdstan, n = 0)) == dim(sim(m7.1_cmdstan, n = 1234))

sim_cmdstan <- sim(fit = m7.1_cmdstan, 
                 data = sim_data,
                 post = extract.samples(
                   object = m7.1_cmdstan
                 ))

sim_data$cmdstan_mean_pred <- apply(sim_cmdstan, 2, mean)

sim_data$cmdstan_mean_pred_sorted <- sort(apply(sim_cmdstan, 2, mean))

# cmdstan's predictions don't follow the data order fed in
cor(sim_data$rstan_mean_pred, sim_data$cmdstan_mean_pred)
cor(sim_data$rstan_mean_pred, sim_data$cmdstan_mean_pred_sorted)

#

sim_data

```

**Comment by rmcelreath** [comment]
The problem arises from using log_lik=TRUE. I haven't implemented all the rstan features into the cmdstan interface, because they keep changing. So the relevant issue here is that models run through cmdstan return *all* parameters. This includes those in generated quantities. So you are getting the mu values in the cmdstan model. Then sim() sees those and uses them.

Set log_lik=FALSE for now. I'll get the remaining cmdstan features implemented.

**Comment by rmcelreath** [comment]
This was an easy fix, and I'll try to run tests and get the fix online later today or tomorrow.

**Comment by DataDan01** [comment]
@rmcelreath Thank you for the quick update here. This package is immensity helpful for my work. The book is excellent as well, I'm a repeat customer from the first edition.

I actually need to set  `log_lik=TRUE` so I can compute PSIS. I'm working on bounded count data where the outcomes are over-dispersed, hence the [issue](https://github.com/rmcelreath/rethinking/issues/267) I opened on dbetabinom.

**Comment by DataDan01** [comment]
@rmcelreath So I downloaded the updated package, 2.13, and ran into some issues. It looks like the predictions are properly ordered now but the PSIS calculation seems to have blown out k values. These high k values are at odds with the reasonable looking `postcheck`. Could this be due to a miss-calculation related to the binomial normalizing constant?

```
library(rethinking)
data(UCBadmit)
d <- UCBadmit
d$gid <- ifelse( d$applicant.gender=="male" , 1L , 2L )
dat <- list( A=d$admit , N=d$applications , gid=d$gid )
m12.1 <- ulam(
    alist(
        A ~ dbetabinom( N , pbar , theta ),
        logit(pbar) <- a[gid],
        a[gid] ~ dnorm( 0 , 1.5 ),
        transpars> theta <<- phi + 2.0,
        phi ~ dexp(1)
    ), data=dat , chains=4 , cmdstan = TRUE, log_lik = TRUE)

PSIS(m12.1, pointwise = TRUE) %>%
    arrange(desc(k)) %>%
    filter(k > 0.5)

postcheck(m12.1)
```

**Comment by rmcelreath** [comment]
I don't see a bug, just a violation of expectations. In these data, each "observation" is an entire department-gender combination. So leaving one "observation" out makes a big difference. It's like the aggregated binomial example on page 337.

But please make another issue for this, if you can show there is a bug.
