### ISSUE TITLE
Variable order requirement for link, sim, ensemble

### ISSUE THREAD

**Issue by michaellevy** [rmcelreath/rethinking#27]
The prediction functions seem to require the variables in `data` to be provided in the order they appear in the model formula. For example:

```
data(nettle)
n = nettle
n$loglpc = log10(n$num.lang / n$k.pop)
n$logArea = log10(n$area)

m = lm(loglpc ~ mean.growing.season * sd.growing.season + log10(area), data = n)
dpred = data.frame(mean.growing.season = 11,
                   sd.growing.season = seq(0, 6, len = 100),
                   logArea = mean(n$logArea))
l = link(m, dpred)
summary(apply(l, 2, mean))

dpred = dpred[, 3:1]
l = link(m, dpred)
summary(apply(l, 2, mean))
```

**Comment by rmcelreath** [comment]
It's not that they require the order to be the same. It's that the data frame will not be defined with the correct number of rows, unless the first variable you define has the right length. Putting sd.growing.season, in your example, first define the correct length. Then R will fill out the single values to all rows.

You could also just make sure each variable is the right length:
```
dpred = data.frame(mean.growing.season = rep(11,100),
                   sd.growing.season = seq(0, 6, len = 100),
                   logArea = rep(mean(n$logArea),100))
```

**Comment by michaellevy** [comment]
I think `data.frame` uses the longest supplied vector to determine the number of rows. Here it does get it right:

```
> dpred = data.frame(mean.growing.season = 11,
+                    sd.growing.season = seq(0, 6, len = 100),
+                    logArea = mean(n$logArea))
> nrow(dpred)
[1] 100
```

Also, explicitly defining the length of each column doesn't fix the issue:

Wrong order, implied length:
```
> m = lm(loglpc ~ mean.growing.season * sd.growing.season + log10(area), data = n)
> dpred = data.frame(mean.growing.season = 11,
+                    sd.growing.season = seq(0, 6, len = 100),
+                    logArea = mean(n$logArea))
> l = link(m, dpred)
> summary(apply(l, 2, mean))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -3.615  -3.112  -2.608  -2.608  -2.105  -1.601 
```

Right order, implied length:
```
> dpred = dpred[, 3:1]
> l = link(m, dpred)
> summary(apply(l, 2, mean))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -2.753  -2.628  -2.502  -2.502  -2.377  -2.251 
```

Wrong order, explicit length:
```
> m = lm(loglpc ~ mean.growing.season * sd.growing.season + log10(area), data = n)
> dpred = data.frame(mean.growing.season = rep(11, 100),
+                    sd.growing.season = seq(0, 6, len = 100),
+                    logArea = rep(mean(n$logArea), 100))
> l = link(m, dpred)
> summary(apply(l, 2, mean))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -3.640  -3.126  -2.612  -2.612  -2.098  -1.584 
```

**Comment by rmcelreath** [comment]
I misunderstood the original issue. Is this behavior that happens only with lm?

The link method for lm is not something I ever finished writing. I could didn't get it to behave right, and couldn't justify spending time on it.

**Comment by michaellevy** [comment]
Yes, the issue seems to be constrained to link for lm's. Maybe add at least a warning to link when called with an lm?

**Comment by rmcelreath** [comment]
I should either fix it or disable it. Might be an easy fix. But bug seems to arise from the way I've hacked into the predict method. So will take a little detective work.
