### ISSUE TITLE
More descriptive name for var2()

### ISSUE THREAD

**Issue by bwiernik** [rmcelreath/rethinking#270]
I'm running into some challenges teaching with students finding it hard to remember what the difference between var() and var2() is. Do you think you could add an alias function with a more descriptive name, such as var_ml()?

**Comment by rmcelreath** [comment]
How about:
```
# aliases
sd_pop <- sd2
var_pop <- var2
```
I don't recall using ``var2`` anywhere but internally, but I must have exposed it someplace if you are seeing it.

**Comment by bwiernik** [comment]
You refer to it in the book. "pop" seems a little misleading when you use it to compute the maximum likelihood estimate of the variance on sample data.
