### ISSUE TITLE
Don't save samples of irrelevant / redundant parameters in map2stan

### ISSUE THREAD

**Issue by paul-buerkner** [rmcelreath/rethinking#28]
First of all, many thanks for this great book and package! 

When playing with the examples in the documentation of `map2stan`, I noticed that using `dmvnormNC` leads to saving parameter samples of `z_N_<group>` and `L_Rho_<group>`. The former samples are irrelevant because they are just `normal(0,1)` and the latter are redundant (in my opinion) as `Rho_<group>` is also saved. Accordingly, I feel that it would make sense to exclude them via the `pars` argument of `stan`. What do you think?

**Comment by rmcelreath** [comment]
I think those transformations should be there by default, so users have information about the underlying algorithm. The primary purpose of map2stan is pedagogy, so I always err on the side of revelation.

If you don't need those redundancies in your context, or you encounter memory constraints, you can use an explicit pars list to get samples for only some of the available parameters. 

Be aware though that there is a hidden "dev" parameter that holds the deviance. It's used to compute DIC. If you omit "dev" from the pars list, DIC calculation will break.

**Comment by paul-buerkner** [comment]
Makes sense, thanks! :-)

**Comment by rmcelreath** [comment]
I'll make a note on this issue to make it easier to remove specific parameters from the returned samples. The idea would be to allow something like:
```
pars_omit=c("L_*","z_*")
```
in the map2stan arguments.

**Comment by paul-buerkner** [comment]
That would certainly be great!
