### ISSUE TITLE
glimmer with family = "binomial"

### ISSUE THREAD

**Issue by expersso** [rmcelreath/rethinking#29]
I can't seem to get `glimmer` to work when `family` is `"binomial"`:

```
glimmer(Species == "virginica" ~ Petal.Width, iris, "binomial")
Error in family$link : $ operator is invalid for atomic vectors
```

Using the standard `glm`, the formula works fine:

```
glm(Species == "virginica" ~ Petal.Width, "binomial", iris)
```

**Comment by expersso** [comment]
My bad, just realized that the family argument just needs to be unquoted:

```
 glimmer(Species == "virginica" ~ Petal.Width, iris, binomial)
```

**Comment by rmcelreath** [comment]
Thanks for documenting this. While easy to fix, it does seem like a bug, in that it doesn't behave like glm.
