### ISSUE TITLE
Error: HDPI not an exported object

### ISSUE THREAD

**Issue by ImranH-cyt** [rmcelreath/rethinking#291]
I am using version 2.13. While running example in R code 3.13, I get the error - 

`HDPI(samples, prob = 0.5)`

Error in HDPI(samples, prob = 0.5) : could not find function "HDPI"

**Comment by torkar** [comment]
Shouldn't it be HPDI()?

**Comment by ImranH-cyt** [comment]
Ah! Silly me! Many thanks @torkar .

**Comment by Flutura1** [comment]
you guys are awesome, I was having the same silly problem. Cheers!
