### ISSUE TITLE
How install rstan dependencies?

### ISSUE THREAD

**Issue by yaitskov** [rmcelreath/rethinking#292]
The practice repo requires to install rstan libraries and refers to project site.

```
First, you need to install rstan
```

I struggle with interpretation of word "install" here, cause [there is](https://github.com/stan-dev/math) no `make install` target or something like that. As for rstan is just bunch of files which compiled together with a c++ program.

How next install step for this practice figures out that I checkout somewhere https://github.com/stan-dev/math???

```
install.packages(c("devtools","mvtnorm","loo","coda"),dependencies=TRUE)
library(devtools)
install_github("rmcelreath/rethinking",ref="Experimental")

```

**Comment by rok-cesnovar** [comment]
You can install Rstan using `install.packages(c("rstan"))`. Stan Math is the backend library for Rstan and other Stan interfaces and you do not need to build/install it separately.

**Comment by rok-cesnovar** [comment]
Also, see https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#installation-of-rstan
