### ISSUE TITLE
precis() issues -- documentation and histograms

### ISSUE THREAD

**Issue by rpruim** [rmcelreath/rethinking#308]
What controls when the histograms are produced by `precis()`?  These are causing trouble (sometimes) for students when they try to knit to PDF.  On the other hand, I've also seen HTML files that don't include the graphs.

The documentation for `precis()` doesn't even mention the plots and the argument list in the documentation doesn't match the signature of the function, so perhaps the documentation is just out of date.

It would be nice if you could run the package through the CRAN checks -- even if you don't submit to CRAN -- to catch things like this.

**Comment by rmcelreath** [comment]
Page 80 of the text explains `hist=FALSE` to suppress the histograms.

**Comment by rpruim** [comment]
Thanks.  That's good to know.  But it would be nice for this to be documented in the package, where it would be much easier to find.

Also I'm seeing 

```r
args(precis)
## function (object, depth = 1, pars, prob = 0.89, digits = 2, sort = NULL, 
##     decreasing = FALSE, ...) 
```

And in precis.Rd I'm seeing

```
\usage{
precis( model , depth=1 , pars , ci=TRUE , prob=0.89 , 
    corr=FALSE , digits=2 , warn=TRUE )
}
%- maybe also 'usage' for other objects documented here.
\arguments{
  \item{model}{Fit model object}
  \item{depth}{If \code{1}, suppresses vectors and matrices of parameters. If \code{2}, displays all parameters}
  \item{pars}{Optional character vector of parameter names to display}
  \item{ci}{Show quadratic estimate confidence intervals}
  \item{prob}{Width of posterior intervals}
  \item{corr}{If \code{TRUE}, show correlations among parameters in output}
  \item{digits}{Number of decimal places to display in output}
  \item{warn}{If \code{TRUE}, warns about various things}
}
```

which doesn't match, doesn't include `...`, and doesn't mention `hist`.
