### ISSUE TITLE
Sampling warning errors

### ISSUE THREAD

**Issue by phasedchirp** [rmcelreath/rethinking#31]
After sampling for all chains has finished, it prints out something like the following:
`Chain 1, Iteration: 1 / 1 [100%]  (Sampling)#`
`#  Elapsed Time: 2e-06 seconds (Warm-up)`
`#                0.000223 seconds (Sampling)`
`#                0.000225 seconds (Total)`
`# `
I then get a warning about a single divergent transition
`There were 1 divergent transitions after warmup. Increasing adapt_delta above 0.X may help.`
where 0.X is some adapt_delta setting (changing it hasn't helped).

This seems to occur no matter what model I'm fitting, including very simple models like the following:
`fakeData <- data.frame(y=rnorm(100,10,5))`
`test <- map2stan(alist(y ~ dnorm(mu,sigma),  mu~dnorm(0,10), sigma~dunif(1,20)), data=fakeData)`

Using `rethinking` v. 1.58. This has occurred with multiple versions of R, running on multiple versions of Ubuntu, and rstan 2.8 and 2.9

**Comment by rmcelreath** [comment]
That final sample is to compute DIC, is my guess. If so, there's no harm in it.

That said, I get no divergent iterations for the example you provide.

**Comment by statwonk** [comment]
<img width="911" alt="screen shot 2018-11-18 at 7 59 13 am" src="https://user-images.githubusercontent.com/1160090/48673530-e3908d80-eb07-11e8-80b2-2d25bc52d471.png">

however when I directly check for divergences I see `0`,

```r
> divergent <- get_sampler_params(test@stanfit, inc_warmup=FALSE)[[1]][,'divergent__']
> sum(divergent)
[1] 0
```

I was lead here by another case where `1` divergence was reported. When I check directly, no divergence. When I look for any sign of the divergence in the `stanfit` object I can find none.

**Comment by abendorf** [comment]
I've run into the same issue.  Below is code that triggers a warning that there was 1 divergent transition after warmup, but the "divergent" function says that there were none.


library(rethinking)
set.seed(123)
# create some fake data for a few different groups
result <- data.frame()
for (i in 1:20)
{
  rand_temp <- sample.int(10,1)
  temp <- data.frame(group=rep(i, rand_temp*5), sample=rnorm(rand_temp*5, ifelse(i %in% c(1,2,3),3,0), 1))
  print(temp)
  result <- rbind(result, temp)
}

# model specification
model_spec <- alist(
  sample ~ dnorm(mu[group], sigma),
  mu[group] ~ dnorm(a, b),
  sigma ~ dcauchy(0, 2.5),
  a ~ dnorm(0, 5),
  b ~ dcauchy(0, 50)
)

# feed the model to stan
mod_obj <- map2stan(model_spec, data = result, iter=10000, control = list(adapt_delta = 0.99))
divergent(mod_obj)

**Comment by rmcelreath** [comment]
This is just the DIC sample taken after real sampling finishes. The way DIC is calculated is to compute the posterior mean and then pass it back into the model to get the deviance.

In the Experimental branch, DIC is disabled by default, I think. I have also phased it out in the new ulam() tool.

**Comment by abendorf** [comment]
Oh, I see.  Thank you very much for clearing that up!  And thanks for this great package.

(By the way, DIC must not be disabled for the Experimental branch, since I got the same message after installing that version.)
