### ISSUE TITLE
Can't produce plot(precis(model)) plots.

### ISSUE THREAD

**Issue by HelenMylne** [rmcelreath/rethinking#324]
The types of plots shown on pages 157 and 331 (for example), using **plot(precis(model))** just do not look on my screen anything even close to the way they do in the book. Book shows an open point (mean) with a black horizontal line (89% compatibility interval). Mine appear as a grid of scatterplots that I am struggling to work out if they show anything useful. Sometimes they have warnings and sometimes they don't. I'm not sure if this is that I haven't loaded the package properly, or if it's a weirdness of my R system (RStudio Version 1.4.1717, R Version 4.0.2).

library(rethinking)
data("chimpanzees")
d <- chimpanzees
d$treatment <- 1 + d$prosoc_left + 2*d$condition
dat_slim <- list(pulled_left = d$pulled_left, actor = d$actor, treatment = as.integer(d$treatment))
m11.4 <- ulam(alist(
                         pulled_left ~ dbinom(1,p),
                         logit(p) <- a[actor] + b[treatment],
                         a[actor] ~ dnorm(0,1.5),
                        b[treatment] ~ dnorm(0,0.5)
       ), data = dat_slim, log_lik = T, chains = 4, cores = 4)
labs <- c('R/N','L/N','R/P','L/P')
plot(precis(m11.4, depth=2, pars='b'), labels = labs)

This one plots with no warning, but completely different to the book:
<img width="889" alt="plot(precis(m11 4))" src="https://user-images.githubusercontent.com/83633954/127902965-b5fbdfbb-faa3-4e4e-bc3b-e0f3d9060200.png">

post <- extract.samples(m11.4)
p_left <- inv_logit(post$a)
plot(precis(as.data.frame(p_left)), xlim = c(0,1))

<img width="871" alt="plot(precis(p_left))" src="https://user-images.githubusercontent.com/83633954/127903280-84674918-57a2-4508-b1ad-98ef3bcb12f9.png">

I also cannot plot the same graph type shown on page 133 using the code plot(coeftab(model1,model2,model3)), this time getting nothing at all but a very similar warning --
Warning message:
In class(x) <- NULL :
  Setting class(x) to NULL;   result will no longer be an S4 object

**Comment by rmcelreath** [comment]
I can't replicate this issue. I guess it is something about your system. All I can suggest is not loading any other packages, reinstalling rethinking, and trying again.

Does the precis output by itself work? If so, then the problem has to do with the plot method not working. You could try calling the method directly:

precis_plot( precis( m11.4 , depth=2 ) )

**Comment by HelenMylne** [comment]
The precis output works, so yeah it's something about plot not reading the precis() output the way it's supposed to. 

precis_plot(precis()) worked perfectly! Thank you!
