### ISSUE TITLE
Adding to generated quantities block

### ISSUE THREAD

**Issue by puterleat** [rmcelreath/rethinking#33]
I'd like to compute estimates of LOO and K-fold cross validation, as described here:

http://www.stat.columbia.edu/~gelman/research/unpublished/waic_stan.pdf

Is there any way to add to the generated quantities block of the stan code maptostan emits to enable one to capture the log likelihood as Gelman et al describe? e.g.

```
generated quantities {
  vector[N] log_lik;
  for (n in 1:N){
         log_lik[n] <- normal_log(y[n], X[n]*b, sigma);
       }
}
```

I realise it's possible to use maptostan first and then extract and edit the code, but this is somewhat of a fiddle. More generally, I wonder if it's possible to include the LL quantity always to enable map2stan fits to be compatible with this LOO package: https://github.com/stan-dev/loo

**Comment by rmcelreath** [comment]
I have a prototype LOO interface in the package already. Look at ``?LOO``. I have not thoroughly tested it however, so be careful.

I think you can get the matrix you want by using the ``pointwise`` and ``loglik`` arguments to the WAIC function:
```
log_lik <- WAIC( fit_model , pointwise=TRUE , loglik=TRUE )
```
That should give you a matrix like your ``log_lik``.
