### ISSUE TITLE
Is there a way to create stan code without fitting a model?

### ISSUE THREAD

**Issue by sdaza** [rmcelreath/rethinking#333]
brms has the function `make_stancode`: 

```
make_stancode(mx ~ time + period + time_period + (time + period + time_period | county), 
    data =  dat, save_model = "src/model.stan")
```

**Comment by torkar** [comment]
stancode(modelName)

**Comment by sdaza** [comment]
Thanks, @torkar. As far as I know, `modelName` has to be a fitted model, right? I don't want to fit the model, just get the stan code.

**Comment by rok-cesnovar** [comment]
I think sample=FALSE in ulam() should do it?

**Comment by sdaza** [comment]
Got it, thank you so much! @rok-cesnovar
