### ISSUE TITLE
Installation fails saying cmdstanr is not available, but it is

### ISSUE THREAD

**Issue by pnojai** [rmcelreath/rethinking#337]
I request help, please, to install the package, rethinking, in R version 4.1.2.

`install_github("rmcelreath/rethinking")`

Fails with message...

```
Skipping 1 packages not available: cmdstanr
Error: Failed to install 'rethinking' from GitHub:
  Multiple results for CXX14FLAGS found, something is wrong.FALSE
```

However, I did install `cmdstanr` and I installed`cmdstan` using `cmdstanr::install_cmdstan(cores = 2)`. I can load the `cmdstanr` library and run the sample code at [Getting Started with CmdStanR](https://mc-stan.org/cmdstanr/articles/cmdstanr.html).

I suspect the package installer doesn't recognize the presence of the `cmdstanr` package because I have the newest release of R. The installer apparently fails to detect the presence of `cmdstanr` even though its installed and usable.

I tried forcing the installation, but that didn't work either: `install_github("rmcelreath/rethinking", force = TRUE)`.

I had no prior installation of Stan on this environment. I did upgrade R from 3.6 to 4.1.

**Environment**
OS: Ubuntu 20.04.3 LTS
R: version 4.1.2 (2021-11-01) -- "Bird Hippie". x86_64-pc-linux-gnu (64-bit)
Installed packages include: coda, mvtnorm, devtools, cmdstanr, bayesplot, posterior, V8

**Comment by rok-cesnovar** [comment]
@pnojai I think the issue that prevents you to install does not stem from the error that mentions cmdstanrr, but rather from `Multiple results for CXX14FLAGS found, something is wrong.FALSE`. This issue seems to be bothering rstan install. 

If you are using RStudio, run `file.edit("~/.R/Makevars")` and see if there are multiple lines with `CXX14FLAGS`

**Comment by pnojai** [comment]
@rok-cesnovar Thanks for the tip. That did it.

My Makevars file contained this:
```

CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
CXX14=g++

CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
CXX14=g++

```

I don't know what process duplicated that configuration. My resolution:

- Copied the file to a backup copy.
- Deleted the duplicate lines.

Now when I installed the package, I got the `usethis` output first, which I didn't see before. I guess it wasn't getting that far. It still says `cmdstanr` is not available, but I suppose that has nothing to do with the installation, as you suggested.

I installed the `rethinking` package and I'm able to load it.

Thanks for your help. I'll close this issue.

```
> library(devtools)
Loading required package: usethis
> install_github("rmcelreath/rethinking")
Downloading GitHub repo rmcelreath/rethinking@HEAD
Skipping 1 packages not available: cmdstanr
✓  checking for file ‘/tmp/Rtmp1WRoGW/remotes231e19c42e0e/rmcelreath-rethinking-783d111/DESCRIPTION’ ... OK
─  preparing ‘rethinking’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘rethinking_2.21.tar.gz’
   
Installing package into ‘/home/jai/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘rethinking’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rethinking)
```

**Comment by pnojai** [comment]
Incidentally, this is why I do everything in virtual machines. I took a snapshot before I did anything with Stan. It has a lot of moving parts and installation isn't straightforward. With the VM snapshot, I retained the option of throwing away all changes and picking up with the prior state of this OS. This turned out not to be a problem with the package or Stan, but if anyone else encounters something like this, the feedback could help them.

**Comment by rasmi** [comment]
I am also getting the message `Skipping 1 packages not available: cmdstanr`, but everything appears to be working fine regardless. This seems to be the [expected behavior when using `devtools::install()`](https://github.com/r-lib/devtools/issues/2230) to install libraries from non-CRAN repos. You can alternatively install via `devtools::install_github("stan-dev/cmdstanr")` (this will install the latest dev version as opposed to the latest release version), or by first [adding the Stan repo to your R environment](https://github.com/stan-dev/cmdstanr/issues/552#issuecomment-930232573), either of which will make it 'available'.

**Comment by jpiaskowski** [comment]
I also had trouble with 'cmdstanr', receiving this message:

```
Warning messages:
1: package ‘cmdstanr’ is not available for this version of R
```

This problem was resolved by visiting the [cmdstanr website](https://mc-stan.org/cmdstanr/) and installing the package via their instruction prior to installing "rethinking":

```
install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

**Comment by rmcelreath** [comment]
# install.packages("remotes")
remotes::install_github("stan-dev/cmdstanr")
