### ISSUE TITLE
Semantic Error when compiling ulam()

### ISSUE THREAD

**Issue by gmeng92** [rmcelreath/rethinking#341]
I just installed the rethinking get the cmdstanr installed correctly.
Everything went quite well when I run the examples on[ this page](https://mc-stan.org/cmdstanr/articles/cmdstanr.html). 
When I followed the Readme.md and ran the following codes:
--------------------------------
`data( UCBadmit )
 UCBadmit$male <- as.integer(UCBadmit$applicant.gender=="male")
UCBadmit$dept <- rep( 1:6 , each=2 )
UCBadmit$applicant.gender <- NULL
m_glmm1 <- ulam(
     alist(
         admit ~ binomial(applications,p),
         logit(p) <- a[dept] + b*male,
         a[dept] ~ normal( abar , sigma ),
         abar ~ normal( 0 , 4 ),
         sigma ~ half_normal(0,1),
         b ~ normal(0,1)
     ), data=UCBadmit )`

--------------------------------
Output throws out Semantic error like this:
--------------------------------------------------------------
Compiling Stan program...
Semantic error in 'C:/Windows/Temp/RtmpSmY4cL/model-5b34c5f3d0a.stan', line 2, column 8 to column 14:
   -------------------------------------------------
     1:  data{
     2:      int reject[12];
                 ^
     3:      int applications[12];
     4:      int admit[12];
   -------------------------------------------------
Identifier 'reject' clashes with reserved keyword.
mingw32-make.exe: *** [make/program:50: C:\Windows\Temp\RtmpSmY4cL\model-5b34c5f3d0a.hpp] Error 1
Error: An error occured during compilation! See the message above for more information.
-----------------------------------------------------------------
I tried more codes using ulam() but all of them returned the same error. Any ideas? Thanks!

**Comment by rmcelreath** [comment]
You have to read the error and respond to it. In this case, remove the reject variable or rename it.

From time to time, the Stan team adds new reserved words. So old examples will stop working. This is why in most of the new lecture examples, I have single letter variable names.
