### ISSUE TITLE
coeftab and precis functions returning hundreds of parameter estimates

### ISSUE THREAD

**Issue by caadams** [rmcelreath/rethinking#348]
When I use coeftab() on a model object from map2stan, the function returns all of the estimated parameters - including the p or mu values for each data point. For example, coeftab(m10.4) returns a[1]  through a[7], bp, bpC, and p[1] through p[504]. This quantity of coefficients makes the plot using plot(coeftab(m10.4)) impossible to read.

precis(m10.4, depth = 2) also returns all of the estimates for p[1] - p[504].

Is there any way to control which parameters are returned for the coeftab() and precis()?

**Comment by rmcelreath** [comment]
precis provides the "pars" argument for selecting variables.

If you are still using map2stan instead of ulam, you will want to switch soon, because map2stan is no longer maintained and eventually it will no longer produce functional Stan code.
