### ISSUE TITLE
Error in library(rethinking) : there is no package called ‘rethinking’

### ISSUE THREAD

**Issue by AliAlmisnid** [rmcelreath/rethinking#359]
I followed the instructions from "Statistical Rethinking" book to install rethinking R package but I get the following error/s, appreciate your support :)

> install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
--- Please select a CRAN mirror for use in this session ---
also installing the dependency ‘StanHeaders’

--- Please select a CRAN mirror for use in this session ---
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://mc-stan.org/r-packages/bin/windows/contrib/4.2/StanHeaders_2.26.13.zip'
Content type 'application/zip' length 3199156 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'https://mc-stan.org/r-packages/bin/windows/contrib/4.2/rstan_2.26.13.zip'
Content type 'application/zip' length 2344412 bytes (2.2 MB)
downloaded 2.2 MB

package ‘StanHeaders’ successfully unpacked and MD5 sums checked
package ‘rstan’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\1436148\AppData\Local\Temp\Rtmp4ItUEb\downloaded_packages
> install.packages(c("coda","mvtorm","devtools","dagitty"))
trying URL 'https://cran.microsoft.com/bin/windows/contrib/4.2/coda_0.19-4.zip'
Content type 'application/zip' length 322820 bytes (315 KB)
downloaded 315 KB

trying URL 'https://cran.microsoft.com/bin/windows/contrib/4.2/devtools_2.4.4.zip'
Content type 'application/zip' length 429179 bytes (419 KB)
downloaded 419 KB

trying URL 'https://cran.microsoft.com/bin/windows/contrib/4.2/dagitty_0.3-1.zip'
Content type 'application/zip' length 298175 bytes (291 KB)
downloaded 291 KB

package ‘coda’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked
package ‘dagitty’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\1436148\AppData\Local\Temp\Rtmp4ItUEb\downloaded_packages
Warning message:
package ‘mvtorm’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
> library(devtools)
Loading required package: usethis
> devtools::install_github("rmcelreath/rethinking")
Downloading GitHub repo rmcelreath/rethinking@HEAD
Skipping 1 packages not available: cmdstanr
Skipping 2 packages ahead of CRAN: StanHeaders, rstan
  
  
  
   checking for file 'C:\Users\1436148\AppData\Local\Temp\Rtmp4ItUEb\remotes4d107fbc48bc\rmcelreath-rethinking-783d111/DESCRIPTION' ...
  
   checking for file 'C:\Users\1436148\AppData\Local\Temp\Rtmp4ItUEb\remotes4d107fbc48bc\rmcelreath-rethinking-783d111/DESCRIPTION' ... 
  
✔  checking for file 'C:\Users\1436148\AppData\Local\Temp\Rtmp4ItUEb\remotes4d107fbc48bc\rmcelreath-rethinking-783d111/DESCRIPTION' (3.1s)

  
  
  
─  preparing 'rethinking': (4.5s)
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
✔  checking DESCRIPTION meta-information

  
  
  
─  checking for LF line-endings in source and make files and shell scripts (2s)

  
  
  
─  checking for empty or unneeded directories

  
  
  
─  looking to see if a 'data/datalist' file should be added

  
  
  
─  building 'rethinking_2.21.tar.gz' (1.3s)

  
   

ERROR: dependency 'cmdstanr' is not available for package 'rethinking'
* removing 'C:/Users/1436148/AppData/Local/Programs/R/R-4.2.1/library/rethinking'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/1436148/AppData/Local/Temp/Rtmp4ItUEb/file4d109f122a1/rethinking_2.21.tar.gz’ had non-zero exit status
> library(rethinking)
Error in library(rethinking) : there is no package called ‘rethinking’

**Comment by rmcelreath** [comment]
You need to install cmdstanr. Instructions here: https://github.com/rmcelreath/rethinking#installation

**Comment by AliAlmisnid** [comment]
Many thanks, it worked
