### ISSUE TITLE
Syntax for blocks

### ISSUE THREAD

**Issue by jonathan-g** [rmcelreath/rethinking#363]
For blocks like `gq` and `transpar`, the `.Rd` documentation and some examples in the code boxes use syntax like 
```
# From code box 15.31
gq> vector[N]:PrC1 <- exp(lpC1)/(exp(lpC1)+exp(lpC0))
```
but in other places, they use syntax like
```
# From code box 13.27
gq> real[1]:x <<- z*exp(v)
```
Code box 14.46 mixes the two:
```
transpars> matrix[10,10]: L_SIGMA <<- cholesky_decompose( SIGMA ),
transpars> matrix[10,10]: SIGMA <- cov_GPL2( Dmat , etasq , rhosq , 0.01 ),
```
Is there a difference between the `<<-` and `<-` syntax? I don't see any explanation of this in the documentation.

**Comment by jacobxk** [comment]
`<<-` denotes to assign the value or output to a global variable, which would be necessary in case the calculation was conducted in a local scope but we want the results go out to the global scope.

**Comment by jonathan-g** [comment]
I get the distinction for R, but It's not clear how that applies in the 
context of an alist that's going to be turned in to STAN code.

m14.8nc <- ulam(
   alist(
     T ~ dpois(lambda),
     lambda <- (a*P^b/g)*exp(k[society]),

     #non-centered Gaussian Process prior
     transpars> vector[10]: k <<- L_SIGMA * z,
     vector[10]: z ~ normal( 0, 1),
     transpars> matrix[10,10]: L_SIGMA <<- cholesky_decompose( SIGMA),
     transpars> matrix[10,10]: SIGMA <- cov_GPL2( Dmat, etasq, rhosq, 0.01),
     c(a,b,g) ~ dexp( 1),
     etasq ~ dexp( 2),
     rhosq ~ dexp( 0.5)
), data=dat_list, chains=4, cores=4, iter=2000)

What is the local/global context for the transpars statements, and what 
is the effect of local vs. global assignment in terms of the generated 
STAN code?

**Comment by rmcelreath** [comment]
I use it to indicate a vectorized operation, in situations where it might be ambiguous what is intended. So vector assignments for example, or basic matrix operations.

What I need to do is write my own list wrapper class so the user could substitute custom operators. The problem with alist() is that is does some parsing, although it is less than list().

**Comment by rmcelreath** [comment]
> What is the local/global context for the `transpars` statements, and what is the effect of local vs. global assignment in terms of the generated STAN code?

transpars statements are placed in Stan's translated parameters block, so they are essentially global. They are also returned in the posterior samples. In the example you quoted, they aren't necessary to get the model to run. I just use them to those variables are returned to the user.

**Comment by jonathan-g** [comment]
Thank you for the clarification.
