### ISSUE TITLE
uniform distribution non compiling with negative values

### ISSUE THREAD

**Issue by AntonioMartini** [rmcelreath/rethinking#38]
The following test model compiles correctly with uniform(0,1) but fails to compile with uniform(-1,1).
Stan doesn't have a problem with uniform(-1,1) so it's something with map2stan I believe.

```
 m2 <- map2stan(
  
    alist(
      
      response ~ dnorm(m, 10),
      m <- k * v1,
      
      k ~ uniform(-1,1)
    ) , 
    data = db,
  )

```

**Comment by rmcelreath** [comment]
Thanks for the report. Also sorry to be slow getting to it.

I think I've figured out the source of the problem. I'll get a fix in the next publish.

In the meantime, you can quote the lower bound to get the correct behavior:
```
 m2 <- map2stan(

    alist(

      response ~ dnorm(m, 10),
      m <- k * v1,

      k ~ uniform("-1",1)
    ) , 
    data = db,
  )
```
