### ISSUE TITLE
Tweaking map2stan traceplots

### ISSUE THREAD

**Issue by zacksteel** [rmcelreath/rethinking#39]
Hi Richard,

I'm hoping you could help me look under the hood on how your package plots the traceplots of map2stan objects. Specifically, is there a way to pull out the plots for just some of the parameters (my current models have dozens and I don't always want to look at all of them). Also, can I adjust the device parameters (e.g., ask or mfrow)?

Thanks for the help

**Comment by zacksteel** [comment]
I figured out the first part: looks like pars=c([names of parameters of interest]) does the trick in limiting the plots.

**Comment by rmcelreath** [comment]
Hi, Zack. Sorry the function isn't better documented. It is in the man pages, under plot.map2stan. Do ?rethinking and you'll find it.

The internal function is called tracerplot, and it is exposed, so you can look at it in R. The header definition is:
```
function (object, pars, col = rethink_palette, alpha = 1, bg = col.alpha("black", 0.15), ask = TRUE, window, n_cols = 3, max_rows = 5, ...)
```
So yes, the arguments ``pars`` and ``n_cols`` and ``max_rows`` will give you what you want, I think.

The argument ``window`` is the interval of samples to show. Defaults to all of them. The others are hopefully self-explanatory.
