### ISSUE TITLE
map2stan function crashing R on RStudio 99.902, R version 3.2.1 for mac

### ISSUE THREAD

**Issue by channelgrubb** [rmcelreath/rethinking#41]
Attempting to recreate the following examples
- ch10, Kline data
- ch08, rugged data

System:
RStudio 99.902, R version 3.2.1 for Mac

Description:
- when loading 'rethinking' library, get the following messages

>  Loading required package: rstan
> Loading required package: ggplot2
> Loading required package: StanHeaders
> rstan (Version 2.10.1, packaged: 2016-06-24 13:22:16 UTC, GitRev: 85f7a56811da)
> For execution on a local, multicore CPU with excess RAM we recommend calling
> rstan_options(auto_write = TRUE)
> options(mc.cores = parallel::detectCores())
> Loading required package: parallel
> rethinking (Version 1.59)
> Warning messages:
> 1: package ‘rstan’ was built under R version 3.2.5 
> 2: package ‘ggplot2’ was built under R version 3.2.4 
> 3: package ‘StanHeaders’ was built under R version 3.2.5

- map function from rethinking library appears to be working properly based on reproducing outputs found in *Statistical Rethinking*
- attempt to use 'map2stan' function and R session aborts without warnings or other error messages
- R session abort occurring for both ch08 and ch10 examples, regardless of how the model is being passed to Stan in the map2Stan function (whether by model variable - e.g. m8.1 - or by full specification of the model in R, as in chapter 8 rugged example).

**Comment by rmcelreath** [comment]
Try updating R. The current version is 3.3.1.
