### ISSUE TITLE
cannot install rethinking 

### ISSUE THREAD

**Issue by newcomer-bio** [rmcelreath/rethinking#416]
Hello 
I'm using RStudio. I tried to install rstan and rethinking as below:

Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1) 
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages(c("coda","mvtnorm","devtools","loo","dagitty","shape"))
devtools::install_github("rmcelreath/rethinking")

It looks rstan was installed. However, an error message popped up every time, removing rethinking. See below:
ERROR: dependency 'cmdstanr' is not available for package 'rethinking'
* removing 'C:/.../R-4.3.0/library/rethinking' 

Can you help resolve this issue? Thank you!

**Comment by rmcelreath** [comment]
Follow the instructions: https://github.com/rmcelreath/rethinking#installation
