### ISSUE TITLE
Rethink package is NOT getting installed

### ISSUE THREAD

**Issue by javadshaterian** [rmcelreath/rethinking#421]
I followed all of these steps, it was not clear in the first step what to add to the PATH - I assumed the exact examples C:\Program Files\GIT\cmd and  C;|Program Files:\Program Files\nodejs seen in the example to be added to the Path
then in the second step files are installed - I think they were supposed to match with PATH 
Finally These commands 
library(rethinking)
globe.qa <- quap(
alist(
W ~ dbinom( W+L ,p) , # binomial likelihood
p ~ dunif(0,1) # uniform prior
) ,
data=list(W=6,L=3) )
# display summary of quadratic approximation
precis( globe.qa )
They were not working command "quap " NOT found
Any solution - any guide if I have gone the wrong ways
Thanks Javad

**Comment by javadshaterian** [comment]
The book is supposed to be a good guide - but I am stopped at "quadratic approximation"

**Comment by javadshaterian** [comment]
C;\Program Files\nodejs  is the correct new path I added with no result

**Comment by javadshaterian** [comment]
By the way, I have Windows 10 working on my computer

**Comment by javadshaterian** [comment]
I installed Package.Rethink  - through the base of it (it is suggested in a separate window that popped up - it did not install by refreshing R first suggestion as for the first suggestion

**Comment by rmcelreath** [comment]
Hi. You are having trouble with the C++ tool chain perhaps. I guess that from the PATH comments. The rethinking package is downstream of that and does nothing directly with it. So I cannot help here in solving your C++ tool chain problem. Lots of Windows people have trouble installing the C++ tool chain though so there is probably a lot of help online.

**Comment by javadshaterian** [comment]
Hi
Thanks for the response
From YouTube - you are an excellent instructor
This is my second book on R modeling -
Having stopped even downloading the required package -  Was this version of
package made for Windows?

As for the PATH change -was it right to add those new command- lines to the
PATH ?  No indicates what to do once
I have opened the edit path
Regards

**Comment by rmcelreath** [comment]
My package is for all platforms that R runs on.

Your troubles have nothing to do with my package, but with dependencies that you have not installed properly. I suspect the C++ tool chain is the problem. 

See https://mc-stan.org/docs/cmdstan-guide/cmdstan-installation.html#windows
