### ISSUE TITLE
Problem installing cmdstanr

### ISSUE THREAD

**Issue by Sayers4697** [rmcelreath/rethinking#429]
I am unable to install cmdstanr. I consistently get the following when I attempt to install. I have tried installing earlier versions and get the same error.  I have not seen any help in Stackoverflow or the Stan group. 

* installing *source* package 'cmdstanr' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'cmdstanr':
 .onLoad failed in loadNamespace() for 'cmdstanr', details:
  call: if (endsWith(path, "/")) {
  error: missing value where TRUE/FALSE needed
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/Gary_/AppData/Local/R/win-library/4.2/cmdstanr'
* restoring previous 'C:/Users/Gary_/AppData/Local/R/win-library/4.2/cmdstanr'

**Comment by rmcelreath** [comment]
This looks like a general Windows package installation bug. Your problem is not specific to cmdstanr (which I did not write). The radical solution is uninstalling your R library completely and starting over. That works for some people. I don't use Windows, so I have no specific advice to offer.
