### ISSUE TITLE
Where is sim_globe, and the rest of the code shown in the videos?

### ISSUE THREAD

**Issue by jameshfisher** [rmcelreath/rethinking#433]
I recently discovered this incredible course! To follow along, I've been trying to find the code that's shown in the videos. I feel a bit stupid, but can't find most of the code.

A concrete example: [there's a function `sim_globe` that's first introduced in the first video here](https://www.youtube.com/watch?v=FdnMWdICdRs&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=1). I've looked in these places but failed to find it:

* [Searching the repo for the 2023 course](https://github.com/search?q=repo%3Armcelreath%2Fstat_rethinking_2023%20sim_globe&type=code) - no results
* [Searching all of https://github.com/rmcelreath](https://github.com/search?q=owner%3Armcelreath%20sim_globe&type=code) - no results
* https://xcelab.net/rmpubs/sr2/code.txt has some things I recognize but not `sim_globe` ...?
* [Searching all of GitHub](https://github.com/search?q=sim_globe&type=code) - some results but none seem "official"?

**Comment by rmcelreath** [comment]
Most of the examples are either in the book or in the scripts folder: https://github.com/rmcelreath/stat_rethinking_2024/tree/main/scripts

sim_globe() is defined in the second lecture in the 2023 series.

**Comment by jameshfisher** [comment]
@rmcelreath perfect, thanks! No problem if a few things are only in the slides. I just wanted to confirm I wasn't missing anything. Thanks again for this amazing course!
