### ISSUE TITLE
The garden of forking data - 2 blue from 1?

### ISSUE THREAD

**Issue by maia-munteanu** [rmcelreath/rethinking#435]
Hi!

I'm working my way through the book and just got to Chapter 2 - the garden of forking data example. Maybe there's something I'm fundamentally misunderstanding about the example (and apologies if this is a rather dumb question) - but how can a bag with 1 blue and 3 white marbles yield 2 blue and 1 white after 3 were removed from the bag? In the case of wwww and bbbb, it is explicitly stated that there are no ways in which these conjectures can arrive at the observed data, but isn't it the case for bwww as well?

And a slightly related question: why consider paths that violate the conjecture bwww (only one blue is present and we sample without replacement)? If one blue is removed first and we assume bwww is correct, then we only have 3 paths: white, white, and white. If we remove white on the first go, we only have blue, white, and white left. If our conjecture is bwww, why is it necessary to consider paths that are not possible given the original assumptions? 

Thanks,
Maia

**Comment by maia-munteanu** [comment]
Ah - missed a critical piece of info:)  

> We do have some evidence: A sequence of three marbles is pulled from the bag, one at a time, replacing the marble each time and shaking the bagbefore drawing another marble.

**Comment by rmcelreath** [comment]
Yeah the bag metaphor is not the clearest. The globe/dice presentation in the most recent lectures is maybe clearer. See lecture 2: https://github.com/rmcelreath/stat_rethinking_2024?tab=readme-ov-file#calendar--topical-outline

**Comment by maia-munteanu** [comment]
Thank you, I will check it out!
