### ISSUE TITLE
Consistent syntax error on map2stan/ulam issues

### ISSUE THREAD

**Issue by jtraeger** [rmcelreath/rethinking#437]
I am working through the second edition of rethinking and am having difficulty getting through chapter 8 with map2stan. For example, R code 8.15 as follows:

```
m8.2<-map2stan(
  alist(
    y~dnorm(mu,sigma),
    mu<-alpha
  ),
  cmdstan=TRUE,data=list(y=y),start=list(alpha=0,sigma=1),
  chains=2,iter=4000,warmup=1000
)

```

(note the argument cmdstan=TRUE, I've added this to some of my ulam codes and it appears to help in some cases, in other cases it doesn't appear to have any effect)
yields the following error,

```
Warning in map2stan(alist(y ~ dnorm(mu, sigma), mu <- alpha, alpha ~ dnorm(1,  :
  DEPRECATED: map2stan is no longer supported and may behave unpredictably or stop working altogether. Start using ulam instead.
Compiling Stan program...
Syntax error in 'C:/Users/jetr4/AppData/Local/Temp/RtmpCWzpQn/model-6f68272920ac.stan', line 4, column 11 to column 12, parsing error:
   -------------------------------------------------
     2:  data{
     3:      int<lower=1> N;
     4:      real y[N];
                    ^
     5:  }
     6:  parameters{
   -------------------------------------------------

";" expected after variable declaration.
It looks like you are trying to use the old array syntax.
Please use the new syntax:
array[N] real y;

mingw32-make: *** [make/program:64: C:/Users/jetr4/AppData/Local/Temp/RtmpCWzpQn/model-6f68272920ac.hpp] Error 1

Error : An error occured during compilation! See the message above for more information.
Error in map2stan(alist(y ~ dnorm(mu, sigma), mu <- alpha, alpha ~ dnorm(1,  : 
  Something went wrong, when calling Stan. Check any debug messages for clues, detective.
An error occured during compilation! See the message above for more information.
```

There does appear to be a .stan file created in the directory noted in the Syntax error. However, it's not clear what changes to my R input I need to do to change this.

I have been moderately successful at substituting "ulam" for "map2stan" earlier in the chapter, but there are certain functionalities like DIC and WAIC that are incompatible with its model (I have seen this in other posts). Furthermore, when I try the above code using ulam instead of map2stan, I get the following error instead:

```
m8.2<-ulam(
  alist(
    y~dnorm(mu,sigma),
    mu<-alpha
  ),
  cmdstan=TRUE,data=list(y=y),start=list(alpha=0,sigma=1),
  chains=2,iter=4000,warmup=1000
)
```

I have tried implementing very flat large uniform priors as a fix in case it just wants really flat priors (alpha<-unif(-1e6,1e6) but that does not help. Any feedback would be helpful! It is somewhat discouraging going forward through the rest of the book trying to slog through fixes and workarounds with ulam.

**Comment by rmcelreath** [comment]
map2stan is deprecated and not used at all in second edition. It looks like you are using first edition code. Check the R code file here for 2nd edition: https://xcelab.net/rm/

**Comment by jtraeger** [comment]
Egg on my face, I thought I had 2nd edition. Thank you for the quick response!
