### ISSUE TITLE
Model descriptions in book chapter 4 don't always match with code

### ISSUE THREAD

**Issue by kuruga** [rmcelreath/rethinking#44]
This is mostly an issue for the textbook chapter 4.

In some cases the model definitions given in the book don't match with the corresponding R code. Furthermore the book references code which doesn't appear.

Examples: 
- page 87, R code for mu
- page 95, R code for alpha
- page 96, The text mentions a `start` list for the model but the R code doesn't contain such a list.

**Comment by Gijs-Koot** [comment]
+1 for this one, in particular the code on page 96 omits start values, and without it the approximation doesn't work. Not necessarily bad for educational purposes, but it is inconsistent.

**Comment by rmcelreath** [comment]
Thanks. These appear to be in the errata list already, aside from the start list mention.

https://github.com/rmcelreath/rethinking/blob/master/ERRATA.md
