### ISSUE TITLE
Bug in plot.map2stan

### ISSUE THREAD

**Issue by herulor** [rmcelreath/rethinking#63]
When selecting a subset of parameters for plotting the traces from a map2stan object, the method plot does not correctly select their n_eff.
Consider the model from the example in the help file to map2stan and compare
precis(m2)
precis(m2, pars = c('bp', 'bpc'))
plot(m2, pars = c('bp', 'bpc'))
The plot shows n_eff for the first two parameters instead of the selected ones.

[Package rethinking version 1.59]

**Comment by rmcelreath** [comment]
This is fixed in the experimental branch.
