### ISSUE TITLE
Error in map for binomial distribution

### ISSUE THREAD

**Issue by fusaroli** [rmcelreath/rethinking#66]
When trying to estimate a rate in a binomial distribution, I get a error if the amount of 1s (or 0s) is the same as the amount of trials. E.g. 

```
trial.qa <- map(
    alist(
        w ~ dbinom(2,p) ,  # binomial likelihood
        p ~ dunif(0,1)
    ) ,
    data=list(w=2) )
```

Or 

```
trial.qa <- map(
    alist(
        w ~ dbinom(2,p) ,  # binomial likelihood
        p ~ dunif(0,1)
    ) ,
    data=list(w=0) )
```

The error is 

> Error in map(alist(w ~ dbinom(2, p), p ~ dunif(0, 1)), data = list(w = 0)) : 
>   non-finite finite-difference value [1]
> Start values for parameters may be too far from MAP.
> Try better priors or use explicit start values.
> If you sampled random start values, just trying again may work.
> Start values used in this attempt:
> p = 0.669026601361111

**Comment by rmcelreath** [comment]
I think this is because ``p`` is not constrained by optim and goes outside the logical bounds [0,1]. Always better to use unconstrained parameters for the fitting level and then transform. So:

```
trial.qa <- map(
    alist(
        w ~ dbinom(2,p) ,  # binomial likelihood
        logit(p) <- a,
        a ~ dnorm(0,10)
    ) ,
    data=list(w=2) )
```

**Comment by fusaroli** [comment]
thanks! I was playing with the globe example in chapter 2 to get the students to change parameters. You might consider changing the code accordingly in the example there (2.4.2) so readers won't stumble upon the same problem :-)

**Comment by rmcelreath** [comment]
I've worried about this. It's too early in Chapter 2 to introduce link functions. What is needed is a way for map() to impose constraints. It could just use the L-BFGS-B method, but the trick is to have map() guess the bounds correctly. Would be a small bit of work, but would require checking the tests on the whole book again, as it's sure to interact badly with some other example.
