### ISSUE TITLE
1.2.1 Rethinking box - ambiguous phrase

### ISSUE THREAD

**Issue by clehene** [rmcelreath/rethinking#75]
> The practical implication is that one can no more infer evolutionary process from a power law than one can infer developmental process from the fact that the height is normally distributed

After reading multiple times trying to figure out what gets compared to what and if there's a typo or some commas missing, I think I can grasp the actual meaning, but not entirely sure. 

meaning 1: "no more" == "not any longer" -e.g.  "one cannot any longer infer evolutionary process from a power law.." seems to conflict with the conjunction ("than")

"one can not infer more (stronger?) evolutionary process from a power law than one can infer developmental process from ...  normal distribution. 

Based on context, I can guess the intention that evolutionary process + power law vs development process + normal height distribution are not comparable.

It could be just me (I'm not an english speaker), but given that this is an important conclusion perhaps it can be rephrased for more clarity?

**Comment by bbolker** [comment]
My rephrasing (not necessarily the best):

> The practical implication is that [it is just as invalid/ridiculous/inappropriate to] infer [some particular properties or characteristics of an] evolutionary process from a power law [as it would be to] infer [properties or characteristics of a] developmental process from the fact that the height is normally distributed.
