### ISSUE TITLE
Categorical interactions with indexing?

### ISSUE THREAD

**Issue by kmiddleton** [rmcelreath/rethinking#81]
I'm trying to work out how to (if) map2stan can fit interactions of categorical predictors with indexing. Imagine two factors, `fctA` and `fctB` with for example 3 levels each. I'm trying to figure out if the map2stan syntax will allow fitting the factorial interaction without going through the model.matrix route and specifying 9 parameter estimates.

The pseudocode in my head would look something like:

```
fctA <- factor(rep(c("AA", "Aa", "aa"), each = 5))
fctB <- factor(rep(c("BB", "Bb", "bb"), each = 5))
y <- rnorm(15)

map2stan(
  alist(
    y ~ dnorm(mu, sigma),
    mu <- a[fctA * fctB],
    a[fctA * fctB] ~ dnorm(0, 1),
    sigma ~ dcauchy(0, 1)
  )
)
```

Is there a way to cajole map2stan's syntax to do this? I don't think there are models like this in Rethinking (but I might be wrong).

**Comment by rmcelreath** [comment]
No, map2stan doesn't do any deep interpretation of the syntax. The design is meant to force the user to do these things manually. A pain, yes, but also the only way I could make students learn how the models are truly specified.

I would use a more automatic package like rstanarm for this kind of thing.
