### ISSUE TITLE
Different results with map2stan

### ISSUE THREAD

**Issue by danilofreire** [rmcelreath/rethinking#9]
Hi Richard!

Congratulations for your new book and your YouTube videos. I find them amazing, I'm learning a lot with them. Today I was replicating some of your examples and I realised that the results obtained with `map()` are quite different from those estimated with `map2stan()`. This gives the right answer: 

```
m4.3 <- map(
	alist(
		height ~ dnorm( mu , sigma ) ,
		mu <- a + b*weight,
		a ~ dnorm( 156 , 100 ) ,
		b ~ dnorm( 0 , 10 ) ,
		sigma ~ dunif( 0 , 50 )
) ,
	data=d2 )
```

But this one does not:

```
m4.3 <- map2stan(
	alist(
		height ~ dnorm( mu , sigma ) ,
		mu <- a + b*weight,
		a ~ dnorm( 156 , 100 ) ,
		b ~ dnorm( 0 , 10 ) ,
		sigma ~ dunif( 0 , 50 )
) ,
	data=d2 )
```

Any leads? Thanks a lot! :)

**Comment by rmcelreath** [comment]
With those priors, I bet the map2stan model isn't converging. Check the n_eff and I bet they'll be very low.

Tighten up the priors, and I bet you'll similar results. Maybe:

```
m4.3 <- map2stan(
    alist(
        height ~ dnorm( mu , sigma ) ,
        mu <- a + b*weight,
        a ~ dnorm( 156 , 10 ) ,
        b ~ dnorm( 0 , 10 ) ,
        sigma ~ dcauchy( 0 , 1 )
) , data=d2 )
```

**Comment by danilofreire** [comment]
Thanks for the quick response. You're right, the model works fine with the cauchy prior. I've just tried running the complete Stan code with `real<lower=0,upper=50> sigma;` and it also doesn't converge. Sorry for the silly question and thanks again for the answer.
