### ISSUE TITLE
map2stan compile error under windows 10

### ISSUE THREAD

**Issue by mpgartland** [rmcelreath/rethinking#90]
Hello- began using your book for my students. Some of the people who are on Windows are getting this error on map2stan when getting into Ch 8. I had no problems with it on my Mac install. Thoughts?

Thanks

Receiving the error below when trying to run this section of code on Windows 10, R version 3.3.3:
m8.1stan <- map2stan(
  alist(
    log_gdp ~ dnorm( mu , sigma ) ,
    mu <- a + bR*rugged + bA*cont_africa + bAR*rugged*cont_africa ,
    a ~ dnorm(0,100),
    bR ~ dnorm(0,10),
    bA ~ dnorm(0,10),
    bAR ~ dnorm(0,10),
    sigma ~ dcauchy(0,2)
  ) ,
  data=dd.trim,iter=2000,warmup = 1000 )

______________________________________________________________________________

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file28403a9b633d.dll" WIN=64 TCLBIN=64 OBJECTS="file28403a9b633d.o"' had status 127 
In addition: Warning messages:
1: running command '"C:/PROGRA~1/R/R-33~1.3/bin//R" CMD config CXX' had status 1 
2: running command 'C:/PROGRA~1/R/R-33~1.3/bin/x64/R CMD SHLIB file28403a9b633d.cpp 2> file28403a9b633d.cpp.err.txt' had status 1 
Error in map2stan(alist(log_gdp ~ dnorm(mu, sigma), mu <- a + bR * rugged +  : 
  Something went wrong, when calling Stan. Check any debug messages for clues, detective.
Compilation ERROR, function(s)/method(s) not created! Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file28403a9b633d.dll" WIN=64 TCLBIN=64 OBJECTS="file28403a9b633d.o"' had status 127

**Comment by csanantonio1** [comment]
I was having the same problem on Windows 7 with version 3.3.1 (and also 3.3.3 after I thought upgrading might help). Eventually, I got an error that included this hyperlink, which has clear instructions for how to fix the issue:

https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Windows#toolchain

My own mistake was during the Rtools installation - I did not select the box to edit the system path and just clicked through with the defaults. Once I reinstalled (selecting the edit path box), I was able to run map2stan no problem.

Hope this helps!
