### ISSUE TITLE
index ordering bug in map2stan

### ISSUE THREAD

**Issue by dvousden** [rmcelreath/rethinking#98]
There is a bug in map2stan when running models with varying intercepts for different levels of a factor. This bug only occurs if there are more than 9 levels. The values are converted to a character and then reordered, i.e. if the levels are 1 through 11, they are reordered to 1, 10,11, 2, 3,4, etc. This then means the coefficient estimates for the different levels are also out of order. This can be identified if you run the same model with map2stan and stan.

Example using fakedata.RData is attached (see rethinking_bug.R to reproduce the error).

[rethinking.zip](https://github.com/rmcelreath/rethinking/files/1046086/rethinking.zip)

**Comment by rmcelreath** [comment]
I believe this is not a bug, but rather the absence of a feature. 

Indexes should be of type integer. I recommend using as.integer() to construct your index variable.

There is some code in the Experimental branch that attempts to protect users from this kind of mistake. So you might try that branch.
